export const products = [

    {
      title: "South of Midnight",
      description:
        "یه بازی جادویی تو جنوب آمریکا که پر از موجودات عجیبه و داستانی عمیق داره. گرافیک و حس و حالش تو رو به یه سفر رویاهامانند می‌بره!",
      img: [
        "https://ts1.mm.bing.net/th?id=OIP.c22hXA-M9POkOfbrJnffrQHaEO&pid=15.1",
        "https://ts1.mm.bing.net/th?id=OIP.ujj1dP_QTlsQ13sEsVclBwHaEc&pid=15.1",
      ],
      quantity: 8,
      price: 1200000,
      category: "game",
      creator: "Compulsion Games",
      stock: true,
      discount: 12,
      rating: 4.3,
      platforms: ["Xbox Series X|S", "PC"],
      releaseYear: 2025,
      gameCategory: "adventure", // Magical adventure
    },
    {
      title: "Forza Horizon 5 (PS5 Edition)",
      description:
        "ماشین‌سواری خفن Forza Horizon 5 حالا برای PS5 اومده و جاده‌هاش نفس‌گیرن. سرعت و گرافیک نسل بعدی منتظرته تا بترکونی!",
      img: [
        "https://ts4.mm.bing.net/th?id=OIP.f5OAt-AwhR1O286cUcSa-AHaHa&pid=15.1",
        "https://ts3.mm.bing.net/th?id=OIP.P0aJ4XrUJr-KughGLIZaiwHaEK&pid=15.1",
      ],
      quantity: 14,
      price: 1250000,
      category: "game",
      creator: "Playground Games",
      stock: true,
      discount: 5,
      rating: 4.6,
      platforms: ["PS5"],
      releaseYear: 2024,
      gameCategory: "simulator", // Racing simulator
    },
    {
      title: "Clair Obscur: Expedition 33",
      description:
        "RPG تاکتیکی با داستانی عمیق که توش با موجودات عجیب می‌جنگی و انتخابات سرنوشتت رو عوض می‌کنه. طراحی هنری و گیم‌پلیش گیمرای حرفه‌ای رو جذب کرده!",
      img: [
        "https://ts2.mm.bing.net/th?id=OIP.RL2428rpKH46kiUSqgjXzAHaLH&pid=15.1",
        "https://ts4.mm.bing.net/th?id=OIP.e9Sgu4pLiR6J3unyOddIFwHaEK&pid=15.1",
      ],
      quantity: 10,
      price: 1300000,
      category: "game",
      creator: "Sandfall Interactive",
      stock: true,
      discount: 7,
      rating: 4.5,
      platforms: ["PS5", "Xbox Series X|S", "PC"],
      releaseYear: 2025,
      gameCategory: "strategy", // Tactical RPG
    },
    {
      title: "The Last of Us Part II Remastered (PC)",
      description:
        "ریمستر شاهکار The Last of Us Part II برای PC با گرافیک بهتر و جزئیات بیشتر اومده. داستان احساسی و اکشنش هنوزم اشک و هیجان رو قاطی می‌کنه!",
      img: [
        "https://ts4.mm.bing.net/th?id=OIP.JlnTykuhz-iK63fOhfAhzQHaKS&pid=15.1",
        "https://ts4.mm.bing.net/th?id=OIP.Ohv32Xvc2PjkqCJHOj4L9AHaEK&pid=15.1",
      ],
      quantity: 12,
      price: 1450000,
      category: "game",
      creator: "Naughty Dog",
      stock: true,
      discount: 10,
      rating: 4.8,
      platforms: ["PC"],
      releaseYear: 2024,
      gameCategory: "actionAdventure", // Action-Adventure
    },
    {
      title: "Tales of the Shire",
      description:
        "زندگی آروم و باحال تو دنیای هابیت‌ها که پر از خونه‌های کوچیک و غذای خوشمزه‌ست. برای گیمرایی که دنبال آرامشن و حال خوبن، یه انتخاب عالیه!",
      img: [
        "https://ts2.mm.bing.net/th?id=OIP.juPTn6_7EPBS19VOTTcJMwHaEK&pid=15.1",
        "https://ts1.mm.bing.net/th?id=OIP.VSAGrFx37z__mqlB_GZkzgHaDt&pid=15.1",
      ],
      quantity: 9,
      price: 950000,
      category: "game",
      creator: "Weta Workshop",
      stock: true,
      discount: 15,
      rating: 4.2,
      platforms: ["PS5", "Xbox Series X|S", "PC", "Nintendo Switch"],
      releaseYear: 2025,
      gameCategory: "adventure", // Light adventure
    },
    {
      title: "WWE 2K25",
      description:
        "جدیدترین نسخه کشتی WWE که با گرافیک بهتر و حرکات واقع‌گرایانه‌تر اومده. سوپراستاراتو انتخاب کن و رینگ رو با ضرباتت بترکون!",
      img: [
        "https://ts3.mm.bing.net/th?id=OIP.HseOppdlGmpLWm7QLOmXPAHaDt&pid=15.1",
        "https://ts1.mm.bing.net/th?id=OIP.7XSMRye6Phr1Z7agFUSXGwHaEK&pid=15.1",
        "https://ts4.mm.bing.net/th?id=OIP.qDQPUC48SdMxMdysfm5J6wHaJQ&pid=15.1",
      ],
      quantity: 11,
      price: 1100000,
      category: "game",
      creator: "2K",
      stock: false,
      discount: 8,
      rating: 4.1,
      platforms: ["PS5", "PS4", "Xbox Series X|S", "Xbox One", "PC"],
      releaseYear: 2025,
      gameCategory: "sports", // Sports/Wrestling
    },
    {
      title: "Split Fiction",
      description:
        "یه بازی اکشن کوآپ که دو دنیای مختلف رو قاطی کرده و با دوستات می‌تونی حسابی بترکونی. داستان و گیم‌پلی خلاقانه‌ش یه تجربه جدید و باحاله!",
      img: [
        "https://ts2.mm.bing.net/th?id=OIP.FnrklBiRf3gelkrh16b8DgHaDt&pid=15.1",
        "https://ts2.mm.bing.net/th?id=OIP._mSApBWuGhTjwxbUbXJgzwHaDt&pid=15.1",
      ],
      quantity: 10,
      price: 1350000,
      category: "game",
      creator: "Hazelight",
      stock: false,
      discount: 10,
      rating: 4.4,
      platforms: ["PS5", "Xbox Series X|S", "PC"],
      releaseYear: 2025,
      gameCategory: "actionAdventure", // Cooperative Action-Adventure
    },
    {
      title: "Two Point Museum",
      description:
        "مدیریت موزه بامزه که پر از دایناسور و آثار عجیبه و طنزش حالتو خوب می‌کنه. گیم‌پلی سبکش برای یه عصر آروم و خنده‌دار عالیه!",
      img: [
        "https://ts3.mm.bing.net/th?id=OIP.bG_FfutsvuPvcGCl7zJfjgHaEK&pid=15.1",
        "https://ts2.mm.bing.net/th?id=OIP.JKPXsc89oFfge9wyaCFpngHaEK&pid=15.1",
      ],
      quantity: 8,
      price: 1000000,
      category: "game",
      creator: "Two Point Studios",
      stock: false,
      discount: 12,
      rating: 4.3,
      platforms: ["PS5", "Xbox Series X|S", "PC"],
      releaseYear: 2025,
      gameCategory: "simulator", // Light Simulation
    },
    {
      title: "Xenoblade Chronicles X Definitive",
      description:
        "RPG ژاپنی با دنیای عظیم که ریمستر شده و گرافیک خفنش چشماتو می‌گیره. داستان حماسی و ماجراجوییش برای ساعت‌ها تو رو غرق خودش می‌کنه!",
      img: [
        "https://ts3.mm.bing.net/th?id=OIP.bG_FfutsvuPvcGCl7zJfjgHaEK&pid=15.1",
        "https://ts2.mm.bing.net/th?id=OIP.JKPXsc89oFfge9wyaCFpngHaEK&pid=15.1",
      ],
      quantity: 13,
      price: 1200000,
      category: "game",
      creator: "Monolith Soft",
      stock: true,
      discount: 5,
      rating: 4.6,
      platforms: ["Nintendo Switch"],
      releaseYear: 2025,
      gameCategory: "rpg", // JRPG
    },
    {
      title: "MLB The Show 25",
      description:
        "بیسبال واقعی‌تر از همیشه که با گیم‌پلی نرم و گرافیک نسل بعدی اومده. برای طرفدارای ورزش یه زمین بازی تمام‌عیاره که می‌تونی توش بدرخشی!",
      img: [
        "https://ts3.mm.bing.net/th?id=OIP.bG_FfutsvuPvcGCl7zJfjgHaEK&pid=15.1",
        "https://ts2.mm.bing.net/th?id=OIP.JKPXsc89oFfge9wyaCFpngHaEK&pid=15.1",
      ],
      quantity: 7,
      price: 1050000,
      category: "game",
      creator: "San Diego Studio",
      stock: true,
      discount: 10,
      rating: 4.2,
      platforms: ["PS5", "PS4", "Xbox Series X|S", "Xbox One", "PC"],
      releaseYear: 2025,
      gameCategory: "sports",
    },
    {
      title: "Suikoden I & II HD Remaster",
      description:
        "دو تا کلاسیک JRPG که با کیفیت HD برگشتن و داستاناشون هنوزم دل می‌بره. برای عاشقای نقش‌آفرینی یه نوستالژی خفن و به‌روز شده‌ست!",
      img: [
        "https://ts3.mm.bing.net/th?id=OIP.bG_FfutsvuPvcGCl7zJfjgHaEK&pid=15.1",
        "https://ts2.mm.bing.net/th?id=OIP.JKPXsc89oFfge9wyaCFpngHaEK&pid=15.1",
      ],
      quantity: 9,
      price: 950000,
      category: "game",
      creator: "Konami",
      stock: true,
      discount: 15,
      rating: 4.5,
      platforms: ["PS5", "Xbox Series X|S", "PC", "Nintendo Switch"],
      releaseYear: 2025,
      gameCategory: "rpg",
    },
    {
      title: "Atomfall",
      description:
        "بقای آخرالزمانی تو بریتانیا که پر از رمز و راز و خطره. گیم‌پلی اکشن و اتمسفر سنگینش تو رو تو دنیای خودش غرق می‌کنه!",
      img: [
        "https://ts3.mm.bing.net/th?id=OIP.GgF1Tzmr1pDmResgOqfBdgHaDt&pid=15.1",
        "https://ts1.mm.bing.net/th?id=OIP.GU9jBXZwuO-iqpu2g1DfFgHaEK&pid=15.1",
      ],
      quantity: 10,
      price: 1150000,
      category: "game",
      creator: "Rebellion",
      stock: true,
      discount: 8,
      rating: 4.3,
      platforms: ["PS5", "Xbox Series X|S", "PC"],
      releaseYear: 2025,
      gameCategory: "actionAdventure",
    },
    {
      title: "The Talos Principle: Reawakened",
      description:
        "پازلای فلسفی که با گرافیک جدید برگشتن و ذهنت رو به چالش می‌کشن. داستان عمیقش و گیم‌پلی اعتیادآورش برای فکر کردن و لذت بردن عالیه!",
      img: [
        "https://ts2.mm.bing.net/th?id=OIP.s5eQbRXawQlkk_vuCE_RPQHaEK&pid=15.1",
        "https://ts2.mm.bing.net/th?id=OIP.-ejSb6lZW-akZE4gkl_NOwHaEK&pid=15.1",
      ],
      quantity: 8,
      price: 900000,
      category: "game",
      creator: "Croteam",
      stock: true,
      discount: 20,
      rating: 4.4,
      platforms: ["PS5", "Xbox Series X|S", "PC"],
      releaseYear: 2025,
      gameCategory: "strategy",
    },
    {
      title: "Lunar Remastered Collection",
      description:
        "JRPG کلاسیک Lunar که با کیفیت بهتر و گرافیک آپدیت‌شده برگشته. داستان عاشقانه و ماجراجوییش هنوزم قلب گیمرا رو می‌بره!",
      img: [
        "https://ts3.mm.bing.net/th?id=OIP.tlEtbFwTv-X0s_Mnfj9t1QHaHa&pid=15.1",
        "https://ts2.mm.bing.net/th?id=OIP.CphqawOoHgXpdu1OhbZXQAHaLH&pid=15.1",
      ],
      quantity: 7,
      price: 850000,
      category: "game",
      creator: "Game Arts",
      stock: true,
      discount: 25,
      rating: 4.1,
      platforms: ["PS5", "PC", "Nintendo Switch"],
      releaseYear: 2025,
      gameCategory: "rpg",
    },
    {
      title: "Days Gone (Remastered)",
      description:
        "زامبی‌سواری Days Gone با گرافیک نسل نهم برای PS5 ریمستر شده و حسابی جذابه. موتورسواری تو دنیای پر از زامبی و داستانش تو رو می‌بره تو مود بقا!",
      img: [
        "https://ts2.mm.bing.net/th?id=OIP.IA5V0GuFZpUcmqFQ6XeqVwHaEK&pid=15.1",
        "https://ts4.mm.bing.net/th?id=OIP.TgzKMTmRz4vcDD9VBkwP2gHaEK&pid=15.1",
        "https://ts1.mm.bing.net/th?id=OIP.DF7hsm3AQGvK4VZmPtP5MwHaEK&pid=15.1",
      ],
      quantity: 11,
      price: 1000000,
      category: "game",
      creator: "Bend Studio",
      stock: true,
      discount: 10,
      rating: 4.2,
      platforms: ["PS5"],
      releaseYear: 2024,
      gameCategory: "actionAdventure",
    },
    {
      title: "Rise of the Ronin",
      description:
        "یه بازی سامورایی تو ژاپن قدیم که اکشن و مخفی‌کاری رو قاطی کرده و باحاله. دنیای باز و شمشیرزنیش برای گیمرا یه تجربه ناب و خفنه!",
      img: [
        "https://ts2.mm.bing.net/th?id=OIP._Y6PExm4vVe8eoorMukVxwHaJ4&pid=15.1",
        "https://ts1.mm.bing.net/th?id=OIP.GYmMd3bEd1t7oX9IhKa-HgHaFj&pid=15.1",
      ],
      quantity: 12,
      price: 1400000,
      category: "game",
      creator: "Team Ninja",
      stock: true,
      discount: 7,
      rating: 4.6,
      platforms: ["PS5"],
      releaseYear: 2024,
      gameCategory: "actionAdventure",
    },
    {
      title: "Bleach: Rebirth of Souls",
      description:
        "بازی انیمه‌ای Bleach که پر از شمشیرزنی و مبارزه‌ست و طرفدارای سری رو دیوونه کرده. گرافیک خفن و اکشن سریعش حسابی تو رو تو نقش ایچیگو می‌بره!",
      img: [
        "https://ts2.mm.bing.net/th?id=OIP.j4YtbcsmGJUqLSnytm3vowHaEK&pid=15.1",
        "https://ts2.mm.bing.net/th?id=OIP.j4YtbcsmGJUqLSnytm3vowHaEK&pid=15.1",
      ],
      quantity: 9,
      price: 1100000,
      category: "game",
      creator: "Bandai Namco",
      stock: true,
      discount: 10,
      rating: 4.3,
      platforms: ["PS5", "Xbox Series X|S", "PC"],
      releaseYear: 2025,
      gameCategory: "action",
    },
    {
      title: "Atelier Yumia",
      description:
        "ماجراجویی کیمیاگری جدید تو سری Atelier که گرافیک و داستانش جذابه و دل می‌بره. برای طرفدارای JRPG یه تجربه شیرین و رنگارنگه که ساعت‌ها سرگرمت می‌کنه!",
      img: [
        "https://ts2.mm.bing.net/th?id=OIP.msdfSQHbvFRdKUjxRVNxBgHaEK&pid=15.1",
        "https://ts4.mm.bing.net/th?id=OIP.xZhs7XXnQ734oPnkeUad_wHaEK&pid=15.1",
      ],
      quantity: 8,
      price: 950000,
      category: "game",
      creator: "Gust",
      stock: true,
      discount: 15,
      rating: 4.2,
      platforms: ["PS5", "PC", "Nintendo Switch"],
      releaseYear: 2025,
      gameCategory: "rpg",
    },
    {
      title: "The First Berserker: Khazan",
      description:
        "اکشن خشن و سریع که توش با دشمنای عظیم می‌جنگی و خون همه جا رو می‌گیره. گیم‌پلی نفس‌گیرش برای عاشقای هاردکور ساخته شده و حسابی می‌ترکونه!",
      img: [
        "https://ts2.mm.bing.net/th?id=OIP.4AU-yAXD3P9WmphXXoSY9QHaEK&pid=15.1",
        "https://ts2.mm.bing.net/th?id=OIP.lkK_gHNTxq1YYrVbR0XHzgHaEK&pid=15.1",
      ],
      quantity: 10,
      price: 1200000,
      category: "game",
      creator: "Neople",
      stock: true,
      discount: 8,
      rating: 4.4,
      platforms: ["PS5", "Xbox Series X|S", "PC"],
      releaseYear: 2025,
      gameCategory: "action",
    },
    {
      title: "AI Limit",
      description:
        "جهان‌باز علمی-تخیلی که پر از ربات و ماجراجوییه و تو رو تو آینده غرق می‌کنه. اکشن و داستانش برای گیمرایی که دنبال چیزای جدیدن عالیه!",
      img: [
        "https://ts4.mm.bing.net/th?id=OIP.L1hHnaZuiLLotrkB8ypRbwHaEo&pid=15.1",
        "https://ts2.mm.bing.net/th?id=OIP.gj1hmARQfJK00tycEs_ktQHaNK&pid=15.1",
      ],
      quantity: 9,
      price: 1300000,
      category: "game",
      creator: "Sense Games",
      stock: true,
      discount: 10,
      rating: 4.3,
      platforms: ["PS5", "Xbox Series X|S", "PC"],
      releaseYear: 2025,
      gameCategory: "actionAdventure",
    },
    {
      title: "Commandos: Origins",
      description:
        "استراتژی جنگ جهانی که با ماموریتای تاکتیکی برگشته و ذهنت رو به کار می‌گیره. گیم‌پلی کلاسیکش برای عاشقای استراتژی یه نوستالژی خفنه!",
      img: [
        "https://ts3.mm.bing.net/th?id=OIP.MGNC-0z9rS5_W8-mHngOdAHaEK&pid=15.1",
        "https://ts3.mm.bing.net/th?id=OIP.JBXRAck_U40FJlxFceO6wgHaEK&pid=15.1",
      ],
      quantity: 7,
      price: 1000000,
      category: "game",
      creator: "Claymore Game Studios",
      stock: true,
      discount: 12,
      rating: 4.1,
      platforms: ["PS5", "Xbox Series X|S", "PC"],
      releaseYear: 2025,
      gameCategory: "strategy",
    },
    {
      title: "Fatal Fury: City of the Wolves",
      description:
        "فایتینگ کلاسیک که با گرافیک جدید و مبارزای سریع برگشته. برای طرفدارای بازیای مبارزه‌ای یه تجربه ناب و پرهیجانه!",
      img: [
        "https://ts1.mm.bing.net/th?id=OIP.l8cZzAIFCLLj-2QaRF5_TwHaLH&pid=15.1",
        "https://ts2.mm.bing.net/th?id=OIP.9asnLqy6jDn35VUzrneh0gHaEK&pid=15.1",
      ],
      quantity: 10,
      price: 1150000,
      category: "game",
      creator: "SNK",
      stock: false,
      discount: 8,
      rating: 4.5,
      platforms: ["PS5", "PS4", "Xbox Series X|S", "PC"],
      releaseYear: 2025,
      gameCategory: "action",
    },
    {
      title: "Monster Hunter Wilds",
      description:
        "شکار هیولاها تو دنیای عظیم که با گرافیک نسل بعدی و گیم‌پلی خفن اومده. برای گیمرایی که عاشق چالش و اکشنن، یه شاهکاره!",
      img: [
        "https://ts1.mm.bing.net/th?id=OIP.TAt-uR8HRFSMBJoCsAbEswHaLH&pid=15.1",
        "https://ts1.mm.bing.net/th?id=OIP.TUMRQmSjovhLf8wOemQeYAHaDt&pid=15.1",
      ],
      quantity: 15,
      price: 1500000,
      category: "game",
      creator: "Capcom",
      stock: true,
      discount: 5,
      rating: 4.9,
      platforms: ["PS5", "Xbox Series X|S", "PC"],
      releaseYear: 2025,
      gameCategory: "actionAdventure",
    },
    {
      title: "Civilization VII",
      description:
        "استراتژی ساخت تمدن که با ویژگیای جدید و گرافیک بهتر از همیشه اومده. تاریخ رو خودت بساز و ساعت‌ها تو این بازی غرق شو!",
      img: [
        "https://ts3.mm.bing.net/th?id=OIP.b5k33BES8GGtDMfJUUKxEwHaEK&pid=15.1",
        "https://ts2.mm.bing.net/th?id=OIP.cod8WhIZ-XoVcl0OCU1TewHaEK&pid=15.1",
      ],
      quantity: 12,
      price: 1400000,
      category: "game",
      creator: "Firaxis Games",
      stock: true,
      discount: 10,
      rating: 4.7,
      platforms: ["PS5", "Xbox Series X|S", "PC"],
      releaseYear: 2025,
      gameCategory: "strategy",
    },
    {
      title: "Like a Dragon: Pirate Yakuza",
      description:
        "یاکوزا حالا دزد دریایی شده و تو دریاها ماجراجویی می‌کنه. اکشن و طنزش یه تجربه باحال و متفاوت برای طرفدارای سریه!",
      img: [
        "https://ts3.mm.bing.net/th?id=OIP.b5k33BES8GGtDMfJUUKxEwHaEK&pid=15.1",
        "https://ts2.mm.bing.net/th?id=OIP.cod8WhIZ-XoVcl0OCU1TewHaEK&pid=15.1",
      ],
      quantity: 9,
      price: 1200000,
      category: "game",
      creator: "Ryu Ga Gotoku Studio",
      stock: true,
      discount: 12,
      rating: 4.4,
      platforms: ["PS5", "PS4", "Xbox Series X|S", "PC"],
      releaseYear: 2025,
      gameCategory: "actionAdventure",
    },
    {
      title: "Path of Exile 2",
      description:
        "RPG تاریک و عمیق که برای گیمرای هاردکور ساخته شده و پر از چالش و لوطه. دنیای وسیع و گیم‌پلی پیچیدش تو رو ساعت‌ها نگه می‌داره!",
      img: "https://tse4.mm.bing.net/th?id=OIG4.0W_rzHvUVUrWpUPMebUg&pid=ImgGn",
      quantity: 11,
      price: 1300000,
      category: "game",
      creator: "Grinding Gear Games",
      stock: true,
      discount: 5,
      rating: 4.8,
      platforms: ["PS5", "Xbox Series X|S", "PC"],
      releaseYear: 2024,
      gameCategory: "rpg",
    },
 
    {
      title: "Turtle Beach Stealth 700 Gen 3",
      description:
        "هدست Turtle Beach که با تکنولوژی Superhuman Hearing صداها رو مثل سوپرمن می‌شنوی و دشمناتو پیدا می‌کنی. اتصال دوگانه Bluetooth و 2.4GHz برای گیم و موسیقی عالیه. باتری ۸۵ ساعته‌ش برای گیمرای هاردکور یه گنجه!",
      img: "https://example.com/stealth700.jpg",
      quantity: 17,
      price: 5100000,
      category: "headset",
      creator: "Turtle Beach",
      stock: true,
      discount: 10,
      rating: 4.7,
      releaseYear: 2025,
    },
    {
      title: "Sennheiser GSP 670",
      description:
        "هدست Sennheiser که با صدای استریوی خفنش جزئیات گیم رو بهت نشون می‌ده و غرقت می‌کنه. میکروفون نویزکنسلینگش برای چت تیمی بی‌نقصه و طراحی ارگونومیکش برای گیمای طولانی راحته. کیفیت ساخت آلمانیش حس اطمینان می‌ده!",
      img: "https://example.com/gsp670.jpg",
      quantity: 12,
      price: 5800000,
      category: "headset",
      creator: "Sennheiser",
      stock: true,
      discount: 8,
      rating: 4.6,
      releaseYear: 2023,
    },
    {
      title: "Razer Kraken V4 Pro",
      description:
        "هدست Razer با haptic feedback که لرزشای گیم رو تو سرت حس می‌کنی و هیجانشو دو برابر می‌کنه. صدای THX Spatialش تو رو وسط میدان نبرد می‌بره و میکروفونش برای استریم عالیه. RGB Chromaش هم برای گیمرای باکلاس یه انتخاب خفنه!",
      img: "https://example.com/krakenv4pro.jpg",
      quantity: 19,
      price: 6000000,
      category: "headset",
      creator: "Razer",
      stock: true,
      discount: 12,
      rating: 4.8,
      releaseYear: 2024,
    },
    {
      title: "SteelSeries Arctis Nova 5X",
      description:
        "هدست SteelSeries که با اپلیکیشنش صداها رو برای هر گیمی تنظیم می‌کنی و می‌ترکونی. اتصال چندپلتفرمیش برای PS5، Xbox و PC عالیه و میکروفونش صداتو شفاف می‌کنه. طراحی سبکش برای گیمرای در حال حرکت حرف نداره!",
      img: "https://example.com/arctisnova5x.jpg",
      quantity: 16,
      price: 4700000,
      category: "headset",
      creator: "SteelSeries",
      stock: true,
      discount: 10,
      rating: 4.5,
      releaseYear: 2025,
    },
    {
      title: "Logitech Astro A50 X",
      description:
        "هدست Logitech که با سوئیچر HDMIش بین کنسولا جابه‌جا می‌شی و گیماتو می‌ترکونی. صدای فراگیرش تو رو تو گیم غرق می‌کنه و میکروفونش برای چت تیمی عالیه. طراحی پریمیومش برای گیمرای چندپلتفرمی یه گنجه!",
      img: "https://example.com/astroa50x.jpg",
      quantity: 13,
      price: 6500000,
      category: "headset",
      creator: "Logitech",
      stock: true,
      discount: 15,
      rating: 4.9,
      releaseYear: 2023,
    },
    {
      title: "HyperX Cloud III Wireless",
      description:
        "هدست HyperX که با صدای شفافش جزئیات گیم رو بهت نشون می‌ده و غرقت می‌کنه. باتری ۱۲۰ ساعته‌ش برای گیمرای تنبل معرکه‌ست و میکروفونش برای چت تیمی بی‌نقصه. فوم مموریش برای گیمای طولانی راحتی رو تضمین می‌کنه!",
      img: "https://example.com/cloudiii.jpg",
      quantity: 21,
      price: 5000000,
      category: "headset",
      creator: "HyperX",
      stock: true,
      discount: 10,
      rating: 4.7,
      releaseYear: 2024,
    },
    {
      title: "Corsair HS80 Max",
      description:
        "هدست Corsair با پارچه خنک که تو گیمای طولانی عرق نمی‌کنی و راحتیش دیوونته می‌کنه. صدای Dolby Atmosش تو رو تو گیم غرق می‌کنه و میکروفونش برای چت عالیه. طراحی سبکش برای گیمرای حرفه‌ای یه انتخاب باحاله!",
      img: "https://example.com/hs80max.jpg",
      quantity: 15,
      price: 5300000,
      category: "headset",
      creator: "Corsair",
      stock: true,
      discount: 8,
      rating: 4.6,
      releaseYear: 2025,
    },
    {
      title: "Turtle Beach Atlas Air",
      description:
        "هدست اوپن‌بک Turtle Beach که با صدای وسیعش تو رو تو گیم غرق می‌کنه و جزئیات رو نشون می‌ده. وزن سبکش برای گیمای طولانی عالیه و میکروفونش برای چت تیمی بی‌نقصه. طراحی مینیمالش برای گیمرای خاص‌پسند حرف نداره!",
      img: "https://example.com/atlasair.jpg",
      quantity: 18,
      price: 4800000,
      category: "headset",
      creator: "Turtle Beach",
      stock: true,
      discount: 12,
      rating: 4.5,
      releaseYear: 2024,
    },
    {
      title: "Sennheiser HD 620S",
      description:
        "هدست Sennheiser با صدای بالانس که برای گیم و موسیقی حرف نداره و غرقت می‌کنه. طراحی بسته‌ش نویز رو کم می‌کنه و میکروفون جداگانه‌ش برای چت عالیه. راحتیش برای گیمرای audiophile یه انتخاب خفنه!",
      img: "https://example.com/hd620s.jpg",
      quantity: 10,
      price: 6700000,
      category: "headset",
      creator: "Sennheiser",
      stock: true,
      discount: 10,
      rating: 4.8,
      releaseYear: 2025,
    },
    {
      title: "Razer Barracuda X Chroma",
      description:
        "هدست Razer با RGB که اتاقتو قشنگ می‌کنه و برای گیم و موسیقی عالیه. اتصال چندکاره Bluetooth و 2.4GHzش انعطاف‌پذیری می‌ده و میکروفونش صداتو شفاف می‌کنه. وزن سبکش برای گیمرای در حال حرکت حرف نداره!",
      img: "https://example.com/barracudax.jpg",
      quantity: 23,
      price: 4600000,
      category: "headset",
      creator: "Razer",
      stock: true,
      discount: 10,
      rating: 4.5,
      releaseYear: 2024,
    },
    {
      title: "SteelSeries Arctis GameBuds",
      description:
        "هدست earbud از SteelSeries که با طراحی کوچیکش برای گیمرای پرتحرک عالیه و جا می‌شه تو جیبت. صدای شفافش تو رو تو گیم غرق می‌کنه و میکروفونش برای چت تیمی بی‌نقصه. باتری ۴۰ ساعته‌ش برای گیمای طولانی کافیه!",
      img: "https://example.com/gamebuds.jpg",
      quantity: 16,
      price: 4300000,
      category: "headset",
      creator: "SteelSeries",
      stock: true,
      discount: 8,
      rating: 4.4,
      releaseYear: 2025,
    },
    {
      title: "Logitech G733 Lightspeed",
      description:
        "هدست Logitech با RGB رنگارنگ که حس گیمری بهت می‌ده و برای چت و گیم عالیه. صدای فراگیرش تو رو تو گیم می‌بره و میکروفونش صداتو شفاف می‌کنه. وزن سبک و بند کشیش برای گیمای طولانی راحته!",
      img: "https://example.com/g733.jpg",
      quantity: 19,
      price: 4500000,
      category: "headset",
      creator: "Logitech",
      stock: true,
      discount: 12,
      rating: 4.5,
      releaseYear: 2023,
    },
    {
      title: "HyperX Cloud Stinger 2",
      description:
        "هدست اقتصادی HyperX که با صدای شفافش برای گیمای رقابتی عالیه و دشمناتو پیدا می‌کنی. میکروفون چرخانش برای چت تیمی بی‌نقصه و وزن سبکش راحتی رو تضمین می‌کنه. برای گیمرای با بودجه کم یه انتخاب توپه!",
      img: "https://example.com/stinger2.jpg",
      quantity: 25,
      price: 3800000,
      category: "headset",
      creator: "HyperX",
      stock: true,
      discount: 15,
      rating: 4.3,
      releaseYear: 2023,
    },
    {
      title: "Corsair Void RGB Elite",
      description:
        "هدست Corsair با صدای 7.1 که تو رو تو گیم غرق می‌کنه و جزئیات رو نشون می‌ده. RGB خفنش برای گیمرای باکلاس جذابه و میکروفونش برای چت عالیه. فوم مموریش برای گیمای طولانی راحته و خستت نمی‌کنه!",
      img: "https://example.com/voidrgb.jpg",
      quantity: 14,
      price: 4700000,
      category: "headset",
      creator: "Corsair",
      stock: true,
      discount: 10,
      rating: 4.4,
      releaseYear: 2024,
    },
    {
      title: "Turtle Beach Stealth 500",
      description:
        "هدست Turtle Beach که با صدای باس‌دارش اکشن گیما رو هیجانی‌تر می‌کنه و غرقت می‌کنه. اتصال وایرلسش برای گیمرای پرتحرک عالیه و میکروفونش صداتو شفاف می‌کنه. قیمت مناسبش برای گیمرای اقتصادی یه گنجه!",
      img: "https://example.com/stealth500.jpg",
      quantity: 20,
      price: 4200000,
      category: "headset",
      creator: "Turtle Beach",
      stock: true,
      discount: 8,
      rating: 4.3,
      releaseYear: 2024,
    },
    {
      title: "Sennheiser EPOS H6Pro",
      description:
        "هدست Sennheiser که با صدای اوپن‌بکش جزئیات گیم رو بهت نشون می‌ده و غرقت می‌کنه. میکروفون جداشدنی‌ش برای چت تیمی عالیه و طراحی سبکش برای گیمای طولانی راحته. کیفیت صداش برای audiophile‌ها حرف نداره!",
      img: "https://example.com/h6pro.jpg",
      quantity: 11,
      price: 5900000,
      category: "headset",
      creator: "Sennheiser",
      stock: true,
      discount: 10,
      rating: 4.7,
      releaseYear: 2023,
    },
    {
      title: "Razer Kaira Pro",
      description:
        "هدست Razer که با hapticش لرزشای گیم رو حس می‌کنی و هیجانشو دو برابر می‌کنه. صدای THXش تو رو تو گیم غرق می‌کنه و میکروفونش برای چت تیمی عالیه. اتصال چندپلتفرمیش برای گیمرای همه‌فن‌حریف یه انتخاب خفنه!",
      img: "https://example.com/kairapro.jpg",
      quantity: 17,
      price: 5100000,
      category: "headset",
      creator: "Razer",
      stock: true,
      discount: 12,
      rating: 4.6,
      releaseYear: 2024,
    },
    {
      title: "SteelSeries Arctis 9 Wireless",
      description:
        "هدست SteelSeries با اتصال دوگانه Bluetooth و 2.4GHz که برای گیم و موسیقی عالیه. صدای شفافش تو رو تو گیم می‌بره و میکروفونش صداتو کریستالی می‌کنه. باتری ۲۰ ساعته‌ش برای گیمرای پرمشغله کافیه!",
      img: "https://example.com/arctis9.jpg",
      quantity: 15,
      price: 4800000,
      category: "headset",
      creator: "SteelSeries",
      stock: true,
      discount: 10,
      rating: 4.5,
      releaseYear: 2023,
    },
    {
      title: "Logitech G435 Lightspeed",
      description:
        "هدست Logitech که با وزن فوق‌سبکش برای گیمای طولانی راحته و خستت نمی‌کنه. صدای شفافش جزئیات گیم رو نشون می‌ده و میکروفونش برای چت تیمی عالیه. قیمت مناسبش برای گیمرای جوون یه انتخاب باحاله!",
      img: "https://example.com/g435.jpg",
      quantity: 22,
      price: 3900000,
      category: "headset",
      creator: "Logitech",
      stock: true,
      discount: 15,
      rating: 4.3,
      releaseYear: 2023,
    },
    {
      title: "HyperX Cloud Flight S",
      description:
        "هدست HyperX با صدای 7.1 که تو رو تو گیم غرق می‌کنه و جزئیات رو نشون می‌ده. باتری ۳۰ ساعته‌ش برای گیمرای پرمشغله کافیه و میکروفونش برای چت تیمی عالیه. طراحی ساده‌ش برای گیمرای مینیمال حرف نداره!",
      img: "https://example.com/cloudflights.jpg",
      quantity: 18,
      price: 4500000,
      category: "headset",
      creator: "HyperX",
      stock: true,
      discount: 10,
      rating: 4.4,
      releaseYear: 2024,
    },
    {
      title: "Corsair HS65 Surround",
      description:
        "هدست Corsair که با صدای فراگیرش تو رو وسط گیم می‌بره و هیجانشو زیاد می‌کنه. میکروفون جداشدنی‌ش برای چت تیمی عالیه و فوم مموریش راحتی رو تضمین می‌کنه. قیمت مناسبش برای گیمرای اقتصادی یه گنجه!",
      img: "https://example.com/hs65.jpg",
      quantity: 16,
      price: 4300000,
      category: "headset",
      creator: "Corsair",
      stock: true,
      discount: 8,
      rating: 4.3,
      releaseYear: 2025,
    },
    {
      title: "Turtle Beach Stealth Pro",
      description:
        "هدست Turtle Beach با ANC که نویز رو بلاک می‌کنه و تمرکزت رو تو گیم بالا می‌بره. صدای پانچی‌ش اکشن گیما رو جذاب‌تر می‌کنه و میکروفونش برای استریم عالیه. باتری ۳۰ ساعته‌ش برای گیمرای حرفه‌ای حرف نداره!",
      img: "https://example.com/stealthpro.jpg",
      quantity: 13,
      price: 5700000,
      category: "headset",
      creator: "Turtle Beach",
      stock: true,
      discount: 12,
      rating: 4.8,
      releaseYear: 2023,
    },
    {
      title: "Sennheiser Momentum 4 Gaming",
      description:
        "هدست Sennheiser که با صدای audiophileش برای گیم و موسیقی معرکه‌ست و غرقت می‌کنه. باتری ۶۰ ساعته‌ش برای گیمرای تنبل عالیه و میکروفونش صداتو شفاف می‌کنه. طراحی شیکش برای گیمرای باکلاس یه انتخاب خفنه!",
      img: "https://example.com/momentum4.jpg",
      quantity: 10,
      price: 6300000,
      category: "headset",
      creator: "Sennheiser",
      stock: true,
      discount: 10,
      rating: 4.9,
      releaseYear: 2024,
    },
    {
      title: "Razer BlackShark V2 Hyperspeed",
      description:
        "هدست Razer که با درایورای Titaniumش صدای خفنی بهت می‌ده و تو گیم غرقت می‌کنه. میکروفونش برای چت تیمی بی‌نقصه و وزن سبکش برای گیمای طولانی راحته. اتصال چندکاره‌ش برای گیمرای پرتحرک یه گنجه!",
      img: "https://example.com/hyperspeed.jpg",
      quantity: 20,
      price: 4600000,
      category: "headset",
      creator: "Razer",
      stock: true,
      discount: 10,
      rating: 4.6,
      releaseYear: 2023,
    },
    {
      title: "SteelSeries Arctis 7P+",
      description:
        "هدست SteelSeries که با صدای شفافش برای گیمای PS5 عالیه و جزئیات رو نشون می‌ده. باتری ۳۰ ساعته‌ش برای گیمرای پرمشغله کافیه و میکروفونش صداتو کریستالی می‌کنه. طراحی ارگونومیکش برای گیمای طولانی راحته!",
      img: "https://example.com/arctis7p.jpg",
      quantity: 17,
      price: 4700000,
      category: "headset",
      creator: "SteelSeries",
      stock: true,
      discount: 8,
      rating: 4.5,
      releaseYear: 2024,
    },
    {
      title: "Logitech G Astro A10 Gen 2",
      description:
        "هدست اقتصادی Logitech که با صدای شفافش برای گیمای رقابتی عالیه و دشمناتو پیدا می‌کنی. میکروفونش برای چت تیمی بی‌نقصه و طراحی سبکش برای گیمرای جوون حرف نداره. قیمت مناسبش برای بودجه کم یه انتخاب باحاله!",
      img: "https://example.com/astroa10.jpg",
      quantity: 24,
      price: 3700000,
      category: "headset",
      creator: "Logitech",
      stock: true,
      discount: 15,
      rating: 4.2,
      releaseYear: 2024,
    },
    {
      title: "HyperX CloudX Stinger Core",
      description:
        "هدست HyperX که با صدای باس‌دارش اکشن گیما رو هیجانی‌تر می‌کنه و غرقت می‌کنه. میکروفون چرخانش برای چت تیمی عالیه و وزن سبکش راحتی رو تضمین می‌کنه. برای گیمرای Xbox یه انتخاب اقتصادی و خفنه!",
      img: "https://example.com/cloudx.jpg",
      quantity: 19,
      price: 3900000,
      category: "headset",
      creator: "HyperX",
      stock: true,
      discount: 10,
      rating: 4.3,
      releaseYear: 2023,
    },
    {
      title: "Corsair HS55 Wireless",
      description:
        "هدست Corsair که با صدای فراگیرش تو رو تو گیم می‌بره و جزئیات رو نشون می‌ده. اتصال وایرلسش برای گیمرای پرتحرک عالیه و میکروفونش صداتو شفاف می‌کنه. طراحی سبکش برای گیمای طولانی راحته و خستت نمی‌کنه!",
      img: "https://example.com/hs55.jpg",
      quantity: 16,
      price: 4400000,
      category: "headset",
      creator: "Corsair",
      stock: true,
      discount: 12,
      rating: 4.4,
      releaseYear: 2025,
    },
    {
      title: "Turtle Beach Recon 500",
      description:
        "هدست Turtle Beach که با درایورای ۶۰ میلی‌متریش صدای پانچی بهت می‌ده و تو گیم غرقت می‌کنه. میکروفونش برای چت تیمی بی‌نقصه و طراحی ساده‌ش برای گیمرای مینیمال حرف نداره. قیمت مناسبش برای گیمرای اقتصادی یه گنجه!",
      img: "https://example.com/recon500.jpg",
      quantity: 21,
      price: 4100000,
      category: "headset",
      creator: "Turtle Beach",
      stock: true,
      discount: 10,
      rating: 4.3,
      releaseYear: 2023,
    },
    {
      title: "Sennheiser GSP 370",
      description:
        "هدست Sennheiser با باتری ۱۰۰ ساعته که برای گیمرای تنبل معرکه‌ست و تو رو تنها نمی‌ذاره. صدای شفافش جزئیات گیم رو نشون می‌ده و میکروفونش برای چت تیمی عالیه. طراحی ارگونومیکش برای گیمای طولانی راحته!",
      img: "https://example.com/gsp370.jpg",
      quantity: 12,
      price: 5400000,
      category: "headset",
      creator: "Sennheiser",
      stock: true,
      discount: 8,
      rating: 4.6,
      releaseYear: 2024,
    },
    {
      title: "Razer Kraken X",
      description:
        "هدست اقتصادی Razer که با صدای 7.1 تو رو تو گیم غرق می‌کنه و دشمناتو پیدا می‌کنی. میکروفونش برای چت تیمی بی‌نقصه و وزن سبکش برای گیمای طولانی راحته. برای گیمرای با بودجه کم یه انتخاب خفنه!",
      img: "https://example.com/krakenx.jpg",
      quantity: 25,
      price: 3800000,
      category: "headset",
      creator: "Razer",
      stock: true,
      discount: 15,
      rating: 4.2,
      releaseYear: 2023,
    },
    {
      title: "SteelSeries Arctis 1 Wireless",
      description:
        "هدست SteelSeries که با اتصال وایرلسش برای گیمرای پرتحرک عالیه و آزادی می‌ده. صدای شفافش تو رو تو گیم می‌بره و میکروفونش صداتو شفاف می‌کنه. طراحی ساده‌ش برای گیمرای مینیمال حرف نداره!",
      img: "https://example.com/arctis1.jpg",
      quantity: 18,
      price: 4200000,
      category: "headset",
      creator: "SteelSeries",
      stock: true,
      discount: 10,
      rating: 4.3,
      releaseYear: 2024,
    },
    {
      title: "Logitech G533 Wireless",
      description:
        "هدست Logitech که با صدای 7.1 تو رو تو گیم غرق می‌کنه و جزئیات رو نشون می‌ده. باتری ۱۵ ساعته‌ش برای گیمرای پرمشغله کافیه و میکروفونش برای چت تیمی عالیه. طراحی مشکی‌ش برای گیمرای باکلاس یه انتخاب باحاله!",
      img: "https://example.com/g533.jpg",
      quantity: 20,
      price: 4500000,
      category: "headset",
      creator: "Logitech",
      stock: true,
      discount: 12,
      rating: 4.4,
      releaseYear: 2023,
    },
    {
      title: "HyperX Cloud MIX",
      description:
        "هدست HyperX که با اتصال دوگانه Bluetooth و سیمی برای گیم و موسیقی عالیه. صدای شفافش تو رو تو گیم می‌بره و میکروفونش صداتو کریستالی می‌کنه. طراحی شیکش برای گیمرای چندکاره یه انتخاب خفنه!",
      img: "https://example.com/cloudmix.jpg",
      quantity: 15,
      price: 4800000,
      category: "headset",
      creator: "HyperX",
      stock: true,
      discount: 10,
      rating: 4.5,
      releaseYear: 2024,
    },
    {
      title: "Corsair HS70 Pro",
      description:
        "هدست Corsair که با صدای فراگیرش تو رو وسط گیم می‌بره و هیجانشو زیاد می‌کنه. میکروفون جداشدنی‌ش برای چت تیمی عالیه و فوم مموریش راحتی رو تضمین می‌کنه. باتری ۱۶ ساعته‌ش برای گیمرای پرمشغله کافیه!",
      img: "https://example.com/hs70pro.jpg",
      quantity: 17,
      price: 4600000,
      category: "headset",
      creator: "Corsair",
      stock: true,
      discount: 8,
      rating: 4.4,
      releaseYear: 2025,
    },
    {
      title: "Turtle Beach Elite Atlas Aero",
      description:
        "هدست Turtle Beach که با صدای Waves Nx تو رو تو گیم غرق می‌کنه و جزئیات رو نشون می‌ده. میکروفونش برای چت تیمی بی‌نقصه و طراحی ارگونومیکش برای گیمای طولانی راحته. برای گیمرای حرفه‌ای یه انتخاب توپه!",
      img: "https://example.com/eliteatlas.jpg",
      quantity: 14,
      price: 5100000,
      category: "headset",
      creator: "Turtle Beach",
      stock: true,
      discount: 10,
      rating: 4.6,
      releaseYear: 2023,
    },
    {
      title: "Razer Huntsman V3 Pro",
      description:
        "کیبورد گیمینگ Razer با سوئیچای اپتیکال که سرعتت رو تو گیم مثل رعد و برق می‌کنه. نورپردازی Chroma RGBش چشاتو می‌گیره و بدنه آلومینیومش حس پریمیوم بودن می‌ده. برای گیمرای رقابتی که دنبال دقت و سرعتن، یه انتخاب خفنه!",
      img: "https://example.com/huntsmanv3pro.jpg",
      quantity: 20,
      price: 6200000,
      category: "keyboard",
      creator: "Razer",
      stock: true,
      discount: 10,
      rating: 4.8,
      releaseYear: 2023,
    },
    {
      title: "SteelSeries Apex Pro TKL (2024)",
      description:
        "کیبورد SteelSeries با سوئیچای OmniPoint که فاصله فعال‌سازیش رو خودت تنظیم می‌کنی و می‌ترکونی. صفحه OLEDش دستوراتت رو سریع نشون می‌ده و RGBش برای گیمرای شب‌زنده‌دار عالیه. طراحی جمع‌وجورش برای تورنمنتا یه گنجه!",
      img: "https://example.com/apexpro2024.jpg",
      quantity: 15,
      price: 6800000,
      category: "keyboard",
      creator: "SteelSeries",
      stock: true,
      discount: 8,
      rating: 4.9,
      releaseYear: 2024,
    },
    {
      title: "Logitech G915 TKL Lightspeed",
      description:
        "کیبورد وایرلس Logitech که با سوئیچای کم‌ارتفاعش تایپ و گیم زدن رو نرم‌تر می‌کنه. باتری ۴۰ ساعته‌ش تو رو تو گیم تنها نمی‌ذاره و RGBش با گیمات هماهنگ می‌شه. بدنه آلومینیومش برای گیمرای باکلاس یه انتخاب شیکه!",
      img: "https://example.com/g915tkl.jpg",
      quantity: 18,
      price: 5500000,
      category: "keyboard",
      creator: "Logitech",
      stock: true,
      discount: 12,
      rating: 4.7,
      releaseYear: 2023,
    },
    {
      title: "HyperX Alloy Origins 2",
      description:
        "کیبورد HyperX با سوئیچای مکانیکال خودش که حس کلیک رضایت‌بخشی می‌ده و گیماتو می‌ترکونه. نورپردازی RGBش چشاتو می‌گیره و بدنه فلزیش استحکام بالایی داره. برای گیمرای اقتصادی که دنبال کیفیتن، یه انتخاب توپه!",
      img: "https://example.com/alloyorigins2.jpg",
      quantity: 22,
      price: 4500000,
      category: "keyboard",
      creator: "HyperX",
      stock: true,
      discount: 10,
      rating: 4.6,
      releaseYear: 2024,
    },
    {
      title: "Corsair K100 RGB Optical",
      description:
        "کیبورد Corsair با سوئیچای اپتیکال که سرعت واکنشش تو گیم دیوونته می‌کنه. صفحه AXONش برای ماکروهای پیچیده عالیه و RGB پویاش اتاقتو قشنگ‌تر می‌کنه. بدنه آلومینیوم و wrist restش برای گیمای طولانی حرف نداره!",
      img: "https://example.com/k100rgb.jpg",
      quantity: 14,
      price: 6700000,
      category: "keyboard",
      creator: "Corsair",
      stock: true,
      discount: 15,
      rating: 4.8,
      releaseYear: 2023,
    },
    {
      title: "Keychron K8 Pro",
      description:
        "کیبورد Keychron که با سوئیچای hot-swap خودش بهت آزادی انتخاب می‌ده و تایپ رو لذت‌بخش می‌کنه. اتصال وایرلس و سیمی‌ش برای گیم و کار عالیه و RGBش حس گیمری می‌ده. برای تایپیست‌ها و گیمرای چندکاره یه انتخاب خفنه!",
      img: "https://example.com/k8pro.jpg",
      quantity: 17,
      price: 4800000,
      category: "keyboard",
      creator: "Keychron",
      stock: true,
      discount: 10,
      rating: 4.7,
      releaseYear: 2024,
    },
    {
      title: "Ducky One 3 SF",
      description:
        "کیبورد جمع‌وجور Ducky که با سوئیچای Cherry MXش حس تایپ کلاسیک می‌ده و گیماتو می‌ترکونه. رنگای پاستلیش چشاتو می‌گیره و بدنه محکمش برای حمل و نقل عالیه. برای گیمرای مینیمال و خاص‌پسند یه گنجه!",
      img: "https://example.com/duckyone3sf.jpg",
      quantity: 12,
      price: 5100000,
      category: "keyboard",
      creator: "Ducky",
      stock: true,
      discount: 8,
      rating: 4.6,
      releaseYear: 2023,
    },
    {
      title: "Razer BlackWidow V4 X",
      description:
        "کیبورد Razer با سوئیچای مکانیکال سبز که کلیکای خفنش تو گیم و تایپ دیوونته می‌کنه. نورپردازی RGBش با گیمات سینک می‌شه و wrist restش برای گیمای طولانی راحته. برای گیمرای پرسرعت یه انتخاب باحاله!",
      img: "https://example.com/blackwidowv4x.jpg",
      quantity: 19,
      price: 5600000,
      category: "keyboard",
      creator: "Razer",
      stock: true,
      discount: 12,
      rating: 4.7,
      releaseYear: 2025,
    },
    {
      title: "SteelSeries Apex 9 Mini",
      description:
        "کیبورد SteelSeries با سوئیچای اپتیکال که سرعتت رو تو گیم به اوج می‌رسونه و می‌ترکونی. طراحی ۶۰٪‌ش برای میزای شلوغ عالیه و RGBش حس گیمری می‌ده. برای گیمرای تورنمنت‌باز یه انتخاب جمع‌وجوره!",
      img: "https://example.com/apex9mini.jpg",
      quantity: 16,
      price: 4900000,
      category: "keyboard",
      creator: "SteelSeries",
      stock: false,
      discount: 10,
      rating: 4.6,
      releaseYear: 2024,
    },
    {
      title: "Logitech G713 TKL",
      description:
        "کیبورد Logitech با سوئیچای لمسی که تایپ و گیم زدن رو نرم و لذت‌بخش می‌کنه. نورپردازی RGBش با رنگای پاستلی چشاتو می‌گیره و بدنه سبکش برای حمل راحته. برای گیمرای جوون و تایپیست‌ها یه انتخاب شیکه!",
      img: "https://example.com/g713tkl.jpg",
      quantity: 13,
      price: 5200000,
      category: "keyboard",
      creator: "Logitech",
      stock: true,
      discount: 15,
      rating: 4.5,
      releaseYear: 2023,
    },
    {
      title: "HyperX Alloy Elite 3",
      description:
        "کیبورد HyperX با سوئیچای Red که سرعتت رو تو گیم بالا می‌بره و حس خوبی می‌ده. RGB خفنش چشاتو نوازش می‌کنه و بدنه فلزیش استحکام بالایی داره. برای گیمرای رقابتی که دنبال کیفیتن، یه انتخاب توپه!",
      img: "https://example.com/alloyelite3.jpg",
      quantity: 21,
      price: 4700000,
      category: "keyboard",
      creator: "HyperX",
      stock: true,
      discount: 10,
      rating: 4.6,
      releaseYear: 2025,
    },
    {
      title: "Corsair K70 RGB Pro",
      description:
        "کیبورد Corsair با سوئیچای Cherry MX که حس کلیک کلاسیک می‌ده و گیماتو می‌ترکونه. نورپردازی RGBش با نرم‌افزار iCUE تنظیم می‌شه و بدنه آلومینیومش محکمه. wrist rest مغناطیسیش برای گیمای طولانی یه گنجه!",
      img: "https://example.com/k70rgbpro.jpg",
      quantity: 15,
      price: 5800000,
      category: "keyboard",
      creator: "Corsair",
      stock: true,
      discount: 8,
      rating: 4.7,
      releaseYear: 2024,
    },
    {
      title: "Keychron Q1 Pro",
      description:
        "کیبورد Keychron با بدنه تمام فلزی که حس پریمیوم بودن می‌ده و تایپ رو لذت‌بخش می‌کنه. سوئیچای hot-swapش بهت آزادی انتخاب می‌ده و RGBش برای گیم و کار عالیه. اتصال وایرلسش برای گیمرای چندکاره حرف نداره!",
      img: "https://example.com/q1pro.jpg",
      quantity: 18,
      price: 5300000,
      category: "keyboard",
      creator: "Keychron",
      stock: false,
      discount: 12,
      rating: 4.8,
      releaseYear: 2023,
    },
    {
      title: "Ducky Shine 8",
      description:
        "کیبورد Ducky با سوئیچای Gateron که تایپ و گیم زدن رو نرم‌تر می‌کنه و حس خوبی می‌ده. نورپردازی RGBش چشاتو می‌گیره و طراحی شیکش برای گیمرای خاص‌پسند عالیه. بدنه محکمش برای سال‌ها مثل روز اول می‌مونه!",
      img: "https://example.com/shine8.jpg",
      quantity: 10,
      price: 5900000,
      category: "keyboard",
      creator: "Ducky",
      stock: true,
      discount: 10,
      rating: 4.7,
      releaseYear: 2025,
    },
    {
      title: "Razer DeathStalker V2 Pro",
      description:
        "کیبورد Razer با سوئیچای اپتیکال کم‌ارتفاع که سرعتت رو تو گیم به اوج می‌رسونه. نورپردازی RGBش با گیمات سینک می‌شه و اتصال وایرلسش برای گیمرای پرتحرک عالیه. بدنه باریکش برای میزای شلوغ یه انتخاب خفنه!",
      img: "https://example.com/deathstalkerv2.jpg",
      quantity: 23,
      price: 6500000,
      category: "keyboard",
      creator: "Razer",
      stock: true,
      discount: 10,
      rating: 4.8,
      releaseYear: 2024,
    },
    {
      title: "SteelSeries Apex 5",
      description:
        "کیبورد SteelSeries با سوئیچای هیبریدی که حس مکانیکال و ممبرین رو قاطی می‌کنه و گیماتو می‌ترکونه. صفحه OLEDش دستوراتت رو نشون می‌ده و RGBش حس گیمری می‌ده. برای گیمرای اقتصادی که دنبال امکاناتن، یه انتخاب باحاله!",
      img: "https://example.com/apex5.jpg",
      quantity: 16,
      price: 4600000,
      category: "keyboard",
      creator: "SteelSeries",
      stock: true,
      discount: 8,
      rating: 4.5,
      releaseYear: 2023,
    },
    {
      title: "Logitech G413 SE",
      description:
        "کیبورد Logitech با سوئیچای Tactile که حس تایپ کلاسیک می‌ده و برای گیم و کار عالیه. بدنه آلومینیومش استحکام بالایی داره و نور سفیدش چشاتو اذیت نمی‌کنه. برای گیمرای مینیمال یه انتخاب ساده و خفنه!",
      img: "https://example.com/g413se.jpg",
      quantity: 19,
      price: 4200000,
      category: "keyboard",
      creator: "Logitech",
      stock: true,
      discount: 12,
      rating: 4.4,
      releaseYear: 2024,
    },
    {
      title: "HyperX Alloy FPS Max",
      description:
        "کیبورد HyperX با سوئیچای Blue که کلیکای خفنش تایپ و گیم زدن رو لذت‌بخش می‌کنه. بدنه فلزیش محکمه و نورپردازی RGBش چشاتو می‌گیره. برای گیمرای رقابتی که دنبال دقتن، یه انتخاب توپه!",
      img: "https://example.com/alloyfpsmax.jpg",
      quantity: 25,
      price: 4800000,
      category: "keyboard",
      creator: "HyperX",
      stock: true,
      discount: 15,
      rating: 4.6,
      releaseYear: 2025,
    },
    {
      title: "Corsair K95 RGB Platinum XT",
      description:
        "کیبورد Corsair با سوئیچای Cherry MX که حس کلیک رضایت‌بخشی می‌ده و گیماتو می‌ترکونه. ماکروهای اختصاصیش برای گیمرای حرفه‌ای عالیه و RGBش با گیمات سینک می‌شه. wrist rest چرمش برای گیمای طولانی یه گنجه!",
      img: "https://example.com/k95xt.jpg",
      quantity: 14,
      price: 6100000,
      category: "keyboard",
      creator: "Corsair",
      stock: true,
      discount: 10,
      rating: 4.7,
      releaseYear: 2023,
    },
    {
      title: "Keychron K10 Pro",
      description:
        "کیبورد Keychron با سوئیچای Red که تایپ و گیم زدن رو نرم‌تر می‌کنه و حس خوبی می‌ده. اتصال وایرلس و سیمی‌ش برای گیمرای چندکاره عالیه و RGBش چشاتو نوازش می‌کنه. بدنه آلومینیومش برای سال‌ها مثل روز اول می‌مونه!",
      img: "https://example.com/k10pro.jpg",
      quantity: 20,
      price: 5400000,
      category: "keyboard",
      creator: "Keychron",
      stock: true,
      discount: 8,
      rating: 4.8,
      releaseYear: 2024,
    },
    {
      title: "Ducky Mecha Mini V2",
      description:
        "کیبورد Ducky با طراحی ۶۰٪ که برای میزای شلوغ عالیه و سوئیچای Cherryش گیماتو می‌ترکونه. نورپردازی RGBش چشاتو می‌گیره و بدنه فلزیش استحکام بالایی داره. برای گیمرای تورنمنت‌باز یه انتخاب جمع‌وجوره!",
      img: "https://example.com/mechamini.jpg",
      quantity: 11,
      price: 5700000,
      category: "keyboard",
      creator: "Ducky",
      stock: true,
      discount: 10,
      rating: 4.7,
      releaseYear: 2025,
    },
    {
      title: "Razer Ornata V3 X",
      description:
        "کیبورد Razer با سوئیچای هیبریدی که حس مکانیکال و ممبرین رو قاطی می‌کنه و تایپ رو لذت‌بخش می‌کنه. نورپردازی RGBش با گیمات سینک می‌شه و wrist restش برای گیمای طولانی راحته. برای گیمرای اقتصادی یه انتخاب باحاله!",
      img: "https://example.com/ornatav3x.jpg",
      quantity: 17,
      price: 4300000,
      category: "keyboard",
      creator: "Razer",
      stock: true,
      discount: 12,
      rating: 4.5,
      releaseYear: 2024,
    },
    {
      title: "SteelSeries Apex 7 TKL",
      description:
        "کیبورد SteelSeries با سوئیچای Red که سرعتت رو تو گیم بالا می‌بره و حس خوبی می‌ده. صفحه OLEDش دستوراتت رو نشون می‌ده و RGBش برای گیمرای شب‌زنده‌دار عالیه. طراحی جمع‌وجورش برای تورنمنتا یه گنجه!",
      img: "https://example.com/apex7tkl.jpg",
      quantity: 15,
      price: 5100000,
      category: "keyboard",
      creator: "SteelSeries",
      stock: true,
      discount: 10,
      rating: 4.6,
      releaseYear: 2023,
    },
    {
      title: "Logitech G512 Carbon",
      description:
        "کیبورد Logitech با سوئیچای GX Blue که کلیکای خفنش گیم و تایپ رو لذت‌بخش می‌کنه. نورپردازی RGBش با نرم‌افزار G HUB تنظیم می‌شه و بدنه آلومینیومش محکمه. برای گیمرای رقابتی یه انتخاب ساده و خفنه!",
      img: "https://example.com/g512carbon.jpg",
      quantity: 22,
      price: 4600000,
      category: "keyboard",
      creator: "Logitech",
      stock: true,
      discount: 15,
      rating: 4.5,
      releaseYear: 2024,
    },
    {
      title: "HyperX Alloy Core RGB",
      description:
        "کیبورد HyperX با سوئیچای ممبرین که حس تایپ نرم می‌ده و برای گیم و کار عالیه. نورپردازی RGBش چشاتو می‌گیره و بدنه محکمش برای استفاده روزمره کافیه. برای گیمرای اقتصادی یه انتخاب باحاله!",
      img: "https://example.com/alloycore.jpg",
      quantity: 18,
      price: 3900000,
      category: "keyboard",
      creator: "HyperX",
      stock: true,
      discount: 10,
      rating: 4.3,
      releaseYear: 2023,
    },
    {
      title: "Corsair K60 RGB Pro SE",
      description:
        "کیبورد Corsair با سوئیچای Cherry Viola که حس کلیک رضایت‌بخشی می‌ده و گیماتو می‌ترکونه. نورپردازی RGBش با iCUE تنظیم می‌شه و wrist restش برای گیمای طولانی راحته. برای گیمرای باکلاس یه انتخاب شیکه!",
      img: "https://example.com/k60prose.jpg",
      quantity: 16,
      price: 4900000,
      category: "keyboard",
      creator: "Corsair",
      stock: true,
      discount: 8,
      rating: 4.4,
      releaseYear: 2025,
    },
    {
      title: "Keychron C3 Pro",
      description:
        "کیبورد Keychron با سوئیچای Brown که تایپ و گیم زدن رو نرم‌تر می‌کنه و حس خوبی می‌ده. نورپردازی قرمز یا RGBش برای گیمرای مینیمال عالیه و بدنه محکمش استحکام بالایی داره. برای تایپیست‌ها و گیمرای اقتصادی یه انتخاب توپه!",
      img: "https://example.com/c3pro.jpg",
      quantity: 13,
      price: 4500000,
      category: "keyboard",
      creator: "Keychron",
      stock: true,
      discount: 12,
      rating: 4.5,
      releaseYear: 2024,
    },
    {
      title: "Ducky One 2 RGB TKL",
      description:
        "کیبورد Ducky با سوئیچای Cherry MX که حس تایپ کلاسیک می‌ده و گیماتو می‌ترکونه. نورپردازی RGBش چشاتو نوازش می‌کنه و طراحی جمع‌وجورش برای میزای شلوغ عالیه. برای گیمرای خاص‌پسند یه انتخاب خفنه!",
      img: "https://example.com/duckyone2tkl.jpg",
      quantity: 20,
      price: 5300000,
      category: "keyboard",
      creator: "Ducky",
      stock: true,
      discount: 10,
      rating: 4.6,
      releaseYear: 2023,
    },
    {
      title: "Razer Pro Type Ultra",
      description:
        "کیبورد Razer با سوئیچای Yellow که تایپ و گیم زدن رو بی‌صدا و نرم می‌کنه. اتصال وایرلسش برای گیمرای پرتحرک عالیه و نور سفیدش چشاتو اذیت نمی‌کنه. برای کار و گیم یه انتخاب مینیمال و شیکه!",
      img: "https://example.com/protypeultra.jpg",
      quantity: 17,
      price: 5700000,
      category: "keyboard",
      creator: "Razer",
      stock: true,
      discount: 8,
      rating: 4.7,
      releaseYear: 2024,
    },
    {
      title: "SteelSeries Apex 3 TKL",
      description:
        "کیبورد SteelSeries با سوئیچای ممبرین که حس تایپ نرم می‌ده و برای گیم و کار عالیه. نورپردازی RGBش چشاتو می‌گیره و بدنه ضدآبش برای گیمرای دست‌وپاچلفتی یه گنجه! طراحی جمع‌وجورش برای تورنمنتا حرف نداره!",
      img: "https://example.com/apex3tkl.jpg",
      quantity: 15,
      price: 4200000,
      category: "keyboard",
      creator: "SteelSeries",
      stock: true,
      discount: 10,
      rating: 4.4,
      releaseYear: 2025,
    },
    {
      title: "Logitech G213 Prodigy",
      description:
        "کیبورد Logitech با سوئیچای ممبرین که حس تایپ رضایت‌بخشی می‌ده و برای گیم و کار کافیه. نورپردازی RGBش با گیمات سینک می‌شه و بدنه محکمش برای استفاده روزمره عالیه. برای گیمرای اقتصادی یه انتخاب باحاله!",
      img: "https://example.com/g213prodigy.jpg",
      quantity: 24,
      price: 3800000,
      category: "keyboard",
      creator: "Logitech",
      stock: true,
      discount: 15,
      rating: 4.3,
      releaseYear: 2023,
    },
    {
      title: "HyperX Alloy Rise",
      description:
        "کیبورد HyperX با سوئیچای hot-swap که بهت آزادی انتخاب می‌ده و گیماتو می‌ترکونه. نورپردازی RGBش چشاتو نوازش می‌کنه و بدنه فلزیش استحکام بالایی داره. برای گیمرای حرفه‌ای که دنبال انعطافن، یه انتخاب خفنه!",
      img: "https://example.com/alloyrise.jpg",
      quantity: 19,
      price: 5100000,
      category: "keyboard",
      creator: "HyperX",
      stock: true,
      discount: 10,
      rating: 4.6,
      releaseYear: 2025,
    },
    {
      title: "Corsair K55 RGB Pro XT",
      description:
        "کیبورد Corsair با سوئیچای ممبرین که حس تایپ نرم می‌ده و برای گیم و کار عالیه. ماکروهای اختصاصیش برای گیمرای حرفه‌ای کافیه و RGBش چشاتو می‌گیره. wrist restش برای گیمای طولانی راحته و خستت نمی‌کنه!",
      img: "https://example.com/k55proxt.jpg",
      quantity: 16,
      price: 4400000,
      category: "keyboard",
      creator: "Corsair",
      stock: true,
      discount: 12,
      rating: 4.4,
      releaseYear: 2024,
    },
    {
      title: "Keychron K14",
      description:
        "کیبورد Keychron با سوئیچای Gateron که تایپ و گیم زدن رو لذت‌بخش می‌کنه و حس خوبی می‌ده. اتصال وایرلسش برای گیمرای پرتحرک عالیه و RGBش برای شب‌زنده‌داری حرف نداره. طراحی ۷۰٪‌ش برای میزای شلوغ یه انتخاب باحاله!",
      img: "https://example.com/k14.jpg",
      quantity: 14,
      price: 4900000,
      category: "keyboard",
      creator: "Keychron",
      stock: true,
      discount: 10,
      rating: 4.5,
      releaseYear: 2023,
    },
    {
      title: "Ducky Feather",
      description:
        "کیبورد Ducky با سوئیچای Cherry MX که حس تایپ کلاسیک می‌ده و گیماتو می‌ترکونه. وزن سبکش برای حمل و نقل عالیه و نورپردازی RGBش چشاتو می‌گیره. برای گیمرای تورنمنت‌باز یه انتخاب جمع‌وجور و خفنه!",
      img: "https://example.com/duckyfeather.jpg",
      quantity: 21,
      price: 5600000,
      category: "keyboard",
      creator: "Ducky",
      stock: true,
      discount: 8,
      rating: 4.7,
      releaseYear: 2024,
    },
    {
      title: "Razer DeathAdder V3 Pro",
      description:
        "موس Razer با سنسور 30K که دقتش تو گیم مثل لیزر می‌مونه و دشمناتو نابود می‌کنه. وزن ۶۳ گرمیش انگار پره تو دستته و باتری وایرلسش تا ۹۰ ساعت گیماتو نگه می‌داره. برای گیمرای رقابتی که دنبال سرعت و دقتن، یه انتخاب خفنه!",
      img: "https://example.com/deathadderv3pro.jpg",
      quantity: 20,
      price: 4800000,
      category: "mouse",
      creator: "Razer",
      stock: true,
      discount: 10,
      rating: 4.8,
      releaseYear: 2023,
    },
    {
      title: "Logitech G Pro X Superlight 2",
      description:
        "موس Logitech با وزن ۶۰ گرم که مثل باد تو دستت حرکت می‌کنه و گیماتو می‌ترکونه. سنسور HERO 2ش دقت دیوونه‌کننده‌ای داره و باتری ۹۵ ساعته‌ش برای ماراتون گیمینگ عالیه. برای گیمرای حرفه‌ای تورنمنت یه گنجه!",
      img: "https://example.com/gproxsuperlight2.jpg",
      quantity: 15,
      price: 5200000,
      category: "mouse",
      creator: "Logitech",
      stock: true,
      discount: 8,
      rating: 4.9,
      releaseYear: 2024,
    },
    {
      title: "SteelSeries Aerox 5 Wireless",
      description:
        "موس SteelSeries با طراحی سوراخ‌دار که وزن ۷۴ گرمیش تو رو تو گیم سبک نگه می‌داره. سنسور TrueMove Airش دقت بالایی داره و RGBش چشاتو می‌گیره. برای گیمرای چندکاره که دکمه‌های زیاد می‌خوان، یه انتخاب باحاله!",
      img: "https://example.com/aerox5.jpg",
      quantity: 18,
      price: 4500000,
      category: "mouse",
      creator: "SteelSeries",
      stock: true,
      discount: 12,
      rating: 4.7,
      releaseYear: 2023,
    },
    {
      title: "Corsair Darkstar Wireless",
      description:
        "موس Corsair با ۶ دکمه کناری که ماکروهات رو تو گیم مثل جادو اجرا می‌کنه. سنسور 26Kش دقتشو به اوج می‌رسونه و RGB خفنش اتاقتو قشنگ‌تر می‌کنه. باتری ۸۰ ساعته‌ش برای گیمرای شب‌زنده‌دار حرف نداره!",
      img: "https://example.com/darkstar.jpg",
      quantity: 14,
      price: 4900000,
      category: "mouse",
      creator: "Corsair",
      stock: true,
      discount: 10,
      rating: 4.6,
      releaseYear: 2024,
    },
    {
      title: "HyperX Pulsefire Haste 2",
      description:
        "موس HyperX با وزن ۵۳ گرم که مثل پر تو دستت می‌چرخه و گیماتو می‌ترکونه. سنسور 26Kش دقت بالایی داره و طراحی سوراخ‌دارش برای گیمای سریع عالیه. برای گیمرای رقابتی که دنبال سبکی و سرعتن، یه انتخاب توپه!",
      img: "https://example.com/pulsefirehaste2.jpg",
      quantity: 22,
      price: 4200000,
      category: "mouse",
      creator: "HyperX",
      stock: true,
      discount: 15,
      rating: 4.5,
      releaseYear: 2023,
    },
    {
      title: "Razer Basilisk V3 X Hypershift",
      description:
        "موس Razer با دکمه‌های قابل برنامه‌ریزی که استایل گیمینگت رو به اوج می‌رسونه. سنسور 18Kش دقت خوبی داره و RGB Chromaش با گیمات سینک می‌شه. برای گیمرای چندکاره که دنبال انعطافن، یه انتخاب خفنه!",
      img: "https://example.com/basiliskv3x.jpg",
      quantity: 17,
      price: 4600000,
      category: "mouse",
      creator: "Razer",
      stock: true,
      discount: 10,
      rating: 4.6,
      releaseYear: 2024,
    },
    {
      title: "Logitech G502 X Plus",
      description:
        "موس Logitech با سوئیچای اپتیکال که کلیکاتو سریع‌تر می‌کنه و گیماتو می‌ترکونه. سنسور HERO 25Kش دقت دیوونه‌کننده‌ای داره و RGBش حس گیمری می‌ده. وزن قابل تنظیمش برای هر گیمری یه گنجه!",
      img: "https://example.com/g502xplus.jpg",
      quantity: 12,
      price: 5100000,
      category: "mouse",
      creator: "Logitech",
      stock: true,
      discount: 8,
      rating: 4.7,
      releaseYear: 2023,
    },
    {
      title: "SteelSeries Rival 5",
      description:
        "موس SteelSeries با ۹ دکمه که برای گیمای MMO و FPS عالیه و دستت رو پر می‌کنه. سنسور TrueMove Coreش دقت خوبی داره و طراحی ارگونومیکش برای گیمای طولانی راحته. RGB خفنش برای گیمرای باکلاس یه انتخاب باحاله!",
      img: "https://example.com/rival5.jpg",
      quantity: 19,
      price: 4300000,
      category: "mouse",
      creator: "SteelSeries",
      stock: true,
      discount: 12,
      rating: 4.5,
      releaseYear: 2025,
    },
    {
      title: "Corsair Scimitar Elite Wireless",
      description:
        "موس Corsair با ۱۲ دکمه کناری که برای گیمرای MMO مثل جادو عمل می‌کنه و ماکروهاتو می‌ترکونه. سنسور 26Kش دقت بالایی داره و باتری وایرلسش تا ۱۲۰ ساعت دووم میاره. برای گیمرای حرفه‌ای که دنبال امکاناتن، یه انتخاب خفنه!",
      img: "https://example.com/scimitarwireless.jpg",
      quantity: 16,
      price: 5500000,
      category: "mouse",
      creator: "Corsair",
      stock: true,
      discount: 10,
      rating: 4.8,
      releaseYear: 2024,
    },
    {
      title: "HyperX Pulsefire Dart",
      description:
        "موس HyperX با شارژ وایرلس که دستت رو تو گیم آزاد نگه می‌داره و گیماتو می‌ترکونه. سنسور 16Kش دقت خوبی داره و RGBش چشاتو نوازش می‌کنه. برای گیمرای اقتصادی که دنبال راحتی وایرلسن، یه انتخاب توپه!",
      img: "https://example.com/pulsefiredart.jpg",
      quantity: 13,
      price: 4500000,
      category: "mouse",
      creator: "HyperX",
      stock: true,
      discount: 15,
      rating: 4.4,
      releaseYear: 2023,
    },
    {
      title: "Razer Viper V3 Hyperspeed",
      description:
        "موس Razer با وزن ۵۹ گرم که مثل باد تو دستت می‌چرخه و برای گیمای سریع عالیه. سنسور 30Kش دقت لیزری داره و باتری AAش تا ۲۸۰ ساعت گیماتو نگه می‌داره. برای گیمرای رقابتی یه انتخاب سبک و خفنه!",
      img: "https://example.com/viperv3hyperspeed.jpg",
      quantity: 21,
      price: 4700000,
      category: "mouse",
      creator: "Razer",
      stock: true,
      discount: 10,
      rating: 4.7,
      releaseYear: 2025,
    },
    {
      title: "Logitech G305 Lightspeed",
      description:
        "موس Logitech با سنسور HERO که دقت خوبی داره و برای گیمای سریع کافیه. باتری AAش تا ۲۵۰ ساعت دووم میاره و وزن سبکش برای گیمرای پرتحرک عالیه. برای گیمرای اقتصادی که وایرلس می‌خوان، یه گنجه!",
      img: "https://example.com/g305.jpg",
      quantity: 25,
      price: 3900000,
      category: "mouse",
      creator: "Logitech",
      stock: true,
      discount: 12,
      rating: 4.5,
      releaseYear: 2023,
    },
    {
      title: "SteelSeries Aerox 9 Wireless",
      description:
        "موس SteelSeries با ۱۸ دکمه که برای گیمای MMO و MOBA مثل یه ارتش تو دستته. سنسور TrueMove Airش دقت بالایی داره و طراحی سوراخ‌دارش وزن رو کم می‌کنه. باتری ۱۸۰ ساعته‌ش برای گیمرای هاردکور حرف نداره!",
      img: "https://example.com/aerox9.jpg",
      quantity: 15,
      price: 5300000,
      category: "mouse",
      creator: "SteelSeries",
      stock: true,
      discount: 8,
      rating: 4.6,
      releaseYear: 2024,
    },
    {
      title: "Corsair Katar Elite Wireless",
      description:
        "موس Corsair با وزن ۶۹ گرم که برای گیمای سریع عالیه و دستت رو خسته نمی‌کنه. سنسور 26Kش دقت لیزری داره و باتری وایرلسش تا ۱۱۰ ساعت گیماتو نگه می‌داره. برای گیمرای رقابتی که دنبال سبکی و سرعتن، یه انتخاب باحاله!",
      img: "https://example.com/katarelite.jpg",
      quantity: 18,
      price: 4600000,
      category: "mouse",
      creator: "Corsair",
      stock: true,
      discount: 10,
      rating: 4.5,
      releaseYear: 2025,
    },
    {
      title: "HyperX Pulsefire Raid",
      description:
        "موس HyperX با ۱۱ دکمه که برای گیمای چندکاره مثل MMO و FPS عالیه و ماکروهاتو می‌ترکونه. سنسور 16Kش دقت خوبی داره و طراحی ارگونومیکش برای گیمای طولانی راحته. برای گیمرای اقتصادی که دکمه زیاد می‌خوان، یه انتخاب توپه!",
      img: "https://example.com/pulsefireraid.jpg",
      quantity: 20,
      price: 4100000,
      category: "mouse",
      creator: "HyperX",
      stock: true,
      discount: 12,
      rating: 4.4,
      releaseYear: 2023,
    },
    {
      title: "Razer Naga V2 Pro",
      description:
        "موس Razer با پنل‌های جداشدنی که برای MMO و FPS تطبیق‌پذیره و گیماتو می‌ترکونه. سنسور 30Kش دقت دیوونه‌کننده‌ای داره و باتری وایرلسش تا ۱۵۰ ساعت دووم میاره. برای گیمرای چندکاره که انعطاف می‌خوان، یه گنجه!",
      img: "https://example.com/nagav2pro.jpg",
      quantity: 16,
      price: 5800000,
      category: "mouse",
      creator: "Razer",
      stock: true,
      discount: 10,
      rating: 4.8,
      releaseYear: 2024,
    },
    {
      title: "Logitech G703 Lightspeed",
      description:
        "موس Logitech با سنسور HERO 25K که دقت بالایی داره و برای گیمای رقابتی کافیه. شارژ وایرلسش با پد Powerplay عالیه و طراحی ارگونومیکش دستت رو خسته نمی‌کنه. برای گیمرای حرفه‌ای که راحتی می‌خوان، یه انتخاب خفنه!",
      img: "https://example.com/g703.jpg",
      quantity: 14,
      price: 4700000,
      category: "mouse",
      creator: "Logitech",
      stock: true,
      discount: 8,
      rating: 4.6,
      releaseYear: 2023,
    },
    {
      title: "SteelSeries Prime Wireless",
      description:
        "موس SteelSeries با سنسور TrueMove Pro که دقتش تو گیم مثل لیزر می‌مونه و دشمناتو پیدا می‌کنه. وزن ۸۰ گرمیش برای گیمای سریع عالیه و باتری ۱۰۰ ساعته‌ش گیماتو نگه می‌داره. برای گیمرای تورنمنت‌باز یه انتخاب باحاله!",
      img: "https://example.com/primewireless.jpg",
      quantity: 19,
      price: 4900000,
      category: "mouse",
      creator: "SteelSeries",
      stock: true,
      discount: 10,
      rating: 4.7,
      releaseYear: 2024,
    },
    {
      title: "Corsair Sabre RGB Pro",
      description:
        "موس Corsair با سنسور 18K که دقت خوبی داره و برای گیمای سریع کافیه. وزن ۷۴ گرمیش دستت رو آزاد نگه می‌داره و RGBش چشاتو نوازش می‌کنه. برای گیمرای اقتصادی که دنبال عملکردن، یه انتخاب توپه!",
      img: "https://example.com/sabrergbpro.jpg",
      quantity: 13,
      price: 4200000,
      category: "mouse",
      creator: "Corsair",
      stock: true,
      discount: 15,
      rating: 4.5,
      releaseYear: 2023,
    },
    {
      title: "HyperX Pulsefire Surge",
      description:
        "موس HyperX با سنسور 16K که دقتش تو گیم خوبه و گیماتو می‌ترکونه. RGB 360 درجه‌ش چشاتو می‌گیره و طراحی ارگونومیکش برای گیمای طولانی راحته. برای گیمرای باکلاس که دنبال استایلن، یه گنجه!",
      img: "https://example.com/pulsefiresurge.jpg",
      quantity: 17,
      price: 4300000,
      category: "mouse",
      creator: "HyperX",
      stock: true,
      discount: 10,
      rating: 4.4,
      releaseYear: 2025,
    },
    {
      title: "Razer Orochi V2",
      description:
        "موس Razer با وزن ۶۰ گرم که برای گیمرای پرتحرک عالیه و تو کیف جا می‌شه. سنسور 18Kش دقت خوبی داره و باتری دوگانه‌ش تا ۹۵۰ ساعت دووم میاره. برای گیمرای اقتصادی که وایرلس می‌خوان، یه انتخاب خفنه!",
      img: "https://example.com/orochiv2.jpg",
      quantity: 23,
      price: 4100000,
      category: "mouse",
      creator: "Razer",
      stock: true,
      discount: 12,
      rating: 4.5,
      releaseYear: 2023,
    },
    {
      title: "Logitech G903 Lightspeed",
      description:
        "موس Logitech با سنسور HERO 25K که دقت لیزری داره و برای گیمای رقابتی عالیه. شارژ وایرلسش با Powerplay تو رو تو گیم نگه می‌داره و دکمه‌های قابل تنظیمش انعطاف می‌ده. برای گیمرای حرفه‌ای یه انتخاب باحاله!",
      img: "https://example.com/g903.jpg",
      quantity: 11,
      price: 5600000,
      category: "mouse",
      creator: "Logitech",
      stock: true,
      discount: 10,
      rating: 4.8,
      releaseYear: 2024,
    },
    {
      title: "SteelSeries Sensei Ten",
      description:
        "موس SteelSeries با سنسور TrueMove Pro که دقتش تو گیم مثل ساعت کار می‌کنه و دشمناتو پیدا می‌کنه. طراحی دوطرفه‌ش برای چپ‌دستا و راست‌دستا عالیه و وزن ۹۲ گرمیش راحته. برای گیمرای کلاسیک یه انتخاب خفنه!",
      img: "https://example.com/senseiten.jpg",
      quantity: 16,
      price: 4500000,
      category: "mouse",
      creator: "SteelSeries",
      stock: true,
      discount: 8,
      rating: 4.6,
      releaseYear: 2023,
    },
    {
      title: "Corsair Ironclaw RGB Wireless",
      description:
        "موس Corsair با سنسور 18K که دقت خوبی داره و برای گیمای چندکاره کافیه. طراحی ارگونومیکش برای دستای بزرگ عالیه و باتری وایرلسش تا ۵۰ ساعت گیماتو نگه می‌داره. برای گیمرای MMO که راحتی می‌خوان، یه گنجه!",
      img: "https://example.com/ironclaw.jpg",
      quantity: 20,
      price: 4700000,
      category: "mouse",
      creator: "Corsair",
      stock: true,
      discount: 10,
      rating: 4.5,
      releaseYear: 2025,
    },
    {
      title: "HyperX Pulsefire Core",
      description:
        "موس HyperX با سنسور 6K که دقتش برای گیمای روزمره کافیه و گیماتو می‌ترکونه. RGB ساده‌ش چشاتو نوازش می‌کنه و طراحی ارگونومیکش دستت رو خسته نمی‌کنه. برای گیمرای اقتصادی که دنبال کیفیتن، یه انتخاب باحاله!",
      img: "https://example.com/pulsefirecore.jpg",
      quantity: 18,
      price: 3800000,
      category: "mouse",
      creator: "HyperX",
      stock: true,
      discount: 15,
      rating: 4.3,
      releaseYear: 2023,
    },
    {
      title: "ASUS ROG Swift PG27UQX",
      description:
        "مانیتور 27 اینچی ASUS با رزولوشن 4K که چشاتو با جزئیات دیوونه‌کننده‌ش غرق می‌کنه. رفرش‌ریت 165Hz و G-Syncش گیماتو نرم‌تر از ابریشم می‌کنه. برای گیمرای حرفه‌ای که دنبال بهترینن، یه انتخاب خفنه!",
      img: "https://example.com/pg27uqx.jpg",
      quantity: 15,
      price: 28500000,
      category: "monitor",
      creator: "ASUS",
      stock: true,
      discount: 10,
      rating: 4.9,
      releaseYear: 2023,
    },
    {
      title: "Acer Predator X28",
      description:
        "مانیتور 28 اینچی Acer با رفرش‌ریت 155Hz که گیمای سریع رو مثل باد نشون می‌ده. پنل IPSش رنگای زنده‌ای داره و HDRش چشاتو می‌گیره. برای گیمرای رقابتی که دقت و سرعت می‌خوان، یه گنجه!",
      img: "https://example.com/predatorx28.jpg",
      quantity: 12,
      price: 24500000,
      category: "monitor",
      creator: "Acer",
      stock: true,
      discount: 8,
      rating: 4.7,
      releaseYear: 2024,
    },
    {
      title: "LG UltraGear 32GP850",
      description:
        "مانیتور 32 اینچی LG با رزولوشن QHD که گیماتو با رفرش‌ریت 180Hz می‌ترکونه. پنل Nano IPSش رنگا رو مثل نقاشی نشون می‌ده و زمان پاسخگویی 1msش برای گیمای سریع عالیه. برای گیمرای باکلاس یه انتخاب شیکه!",
      img: "https://example.com/32gp850.jpg",
      quantity: 18,
      price: 22500000,
      category: "monitor",
      creator: "LG",
      stock: true,
      discount: 12,
      rating: 4.8,
      releaseYear: 2023,
    },
    {
      title: "Samsung Odyssey G7 (2024)",
      description:
        "مانیتور 27 اینچی Samsung با پنل QLED که رنگا رو مثل واقعیت نشون می‌ده و چشاتو می‌گیره. رفرش‌ریت 240Hz و انحنای 1000Rش گیماتو غرق‌کننده می‌کنه. برای گیمرای حرفه‌ای که دنبال سرعت و کیفیتن، یه انتخاب توپه!",
      img: "https://example.com/odysseyg7.jpg",
      quantity: 14,
      price: 26500000,
      category: "monitor",
      creator: "Samsung",
      stock: true,
      discount: 10,
      rating: 4.9,
      releaseYear: 2024,
    },
    {
      title: "MSI Optix MAG274QRF",
      description:
        "مانیتور 27 اینچی MSI با رزولوشن QHD که با رفرش‌ریت 165Hz گیماتو نرم و روان می‌کنه. پنل IPSش زاویه دید خفنی داره و RGB پشتش حس گیمری می‌ده. برای گیمرای اقتصادی که کیفیت می‌خوان، یه گنجه!",
      img: "https://example.com/mag274qrf.jpg",
      quantity: 20,
      price: 19500000,
      category: "monitor",
      creator: "MSI",
      stock: true,
      discount: 15,
      rating: 4.6,
      releaseYear: 2023,
    },
    {
      title: "BenQ Zowie XL2566K",
      description:
        "مانیتور 24.5 اینچی BenQ با رفرش‌ریت 360Hz که برای گیمرای esports مثل رعد و برق عمل می‌کنه. پنل TNش زمان پاسخگویی 0.5ms داره و دقتش دشمناتو نابود می‌کنه. برای تورنمنت‌بازای حرفه‌ای یه انتخاب خفنه!",
      img: "https://example.com/xl2566k.jpg",
      quantity: 16,
      price: 23500000,
      category: "monitor",
      creator: "BenQ",
      stock: true,
      discount: 10,
      rating: 4.8,
      releaseYear: 2024,
    },
    {
      title: "Dell Alienware AW3423DWF",
      description:
        "مانیتور 34 اینچی Dell با پنل QD-OLED که رنگای مشکی عمیق و زنده‌ای بهت می‌ده. رزولوشن UWQHD و رفرش‌ریت 175Hz گیماتو غرق‌کننده می‌کنه. برای گیمرای لوکس‌پسند که دنبال کیفیتن، یه انتخاب شیکه!",
      img: "https://example.com/aw3423dwf.jpg",
      quantity: 13,
      price: 32500000,
      category: "monitor",
      creator: "Dell",
      stock: true,
      discount: 8,
      rating: 4.9,
      releaseYear: 2023,
    },
    {
      title: "ASUS TUF VG27AQ3A",
      description:
        "مانیتور 27 اینچی ASUS با رزولوشن QHD که رفرش‌ریت 180Hzش گیماتو نرم‌تر از کره می‌کنه. پنل IPSش رنگا رو دقیق نشون می‌ده و FreeSyncش لگ رو نابود می‌کنه. برای گیمرای اقتصادی که عملکرد می‌خوان، یه انتخاب باحاله!",
      img: "https://example.com/vg27aq3a.jpg",
      quantity: 19,
      price: 18500000,
      category: "monitor",
      creator: "ASUS",
      stock: true,
      discount: 12,
      rating: 4.5,
      releaseYear: 2025,
    },
    {
      title: "Acer Nitro XV272U",
      description:
        "مانیتور 27 اینچی Acer با رفرش‌ریت 170Hz که گیمای سریع رو مثل باد نشون می‌ده. پنل IPSش زاویه دید خفنی داره و HDR10ش رنگا رو زنده‌تر می‌کنه. برای گیمرای با بودجه متوسط یه انتخاب توپه!",
      img: "https://example.com/xv272u.jpg",
      quantity: 17,
      price: 20500000,
      category: "monitor",
      creator: "Acer",
      stock: true,
      discount: 10,
      rating: 4.6,
      releaseYear: 2023,
    },
    {
      title: "LG UltraGear 27GR95QE",
      description:
        "مانیتور 27 اینچی LG با پنل OLED که رنگای مشکی عمیق و کنتراست دیوونه‌کننده‌ای داره. رفرش‌ریت 240Hz و زمان پاسخگویی 0.03ms گیماتو به اوج می‌بره. برای گیمرای پریمیوم که بهترینو می‌خوان، یه گنجه!",
      img: "https://example.com/27gr95qe.jpg",
      quantity: 11,
      price: 34500000,
      category: "monitor",
      creator: "LG",
      stock: true,
      discount: 15,
      rating: 4.9,
      releaseYear: 2024,
    },
    {
      title: "Samsung Odyssey Neo G8",
      description:
        "مانیتور 32 اینچی Samsung با رزولوشن 4K که Mini-LEDش روشنایی و رنگا رو به اوج می‌رسونه. رفرش‌ریت 240Hz و انحنای 1000R گیماتو غرق‌کننده می‌کنه. برای گیمرای لوکس‌پسند یه انتخاب خفنه!",
      img: "https://example.com/odysseyneog8.jpg",
      quantity: 14,
      price: 38500000,
      category: "monitor",
      creator: "Samsung",
      stock: true,
      discount: 10,
      rating: 4.9,
      releaseYear: 2023,
    },
    {
      title: "MSI MAG321CURV",
      description:
        "مانیتور 32 اینچی MSI با انحنای 1500R که گیماتو فراگیر می‌کنه و چشاتو می‌گیره. رزولوشن 4K و رفرش‌ریت 144Hzش برای گیمای سنگین عالیه. برای گیمرای اقتصادی که دنبال کیفیتن، یه انتخاب باحاله!",
      img: "https://example.com/mag321curv.jpg",
      quantity: 20,
      price: 21500000,
      category: "monitor",
      creator: "MSI",
      stock: true,
      discount: 12,
      rating: 4.6,
      releaseYear: 2024,
    },
    {
      title: "BenQ Mobiuz EX2710U",
      description:
        "مانیتور 27 اینچی BenQ با رزولوشن 4K که HDRiش رنگا رو زنده‌تر می‌کنه و گیماتو می‌ترکونه. رفرش‌ریت 144Hz و اسپیکرای داخلیش برای گیم و سرگرمی عالیه. برای گیمرای چندکاره یه انتخاب شیکه!",
      img: "https://example.com/ex2710u.jpg",
      quantity: 16,
      price: 25500000,
      category: "monitor",
      creator: "BenQ",
      stock: true,
      discount: 10,
      rating: 4.7,
      releaseYear: 2023,
    },
    {
      title: "Dell UltraSharp U2724DE",
      description:
        "مانیتور 27 اینچی Dell با رزولوشن QHD که پنل IPSش رنگا رو دقیق نشون می‌ده و گیماتو قشنگ می‌کنه. رفرش‌ریت 120Hz و پورتای متنوعش برای کار و گیم عالیه. برای گیمرای مینیمال که کیفیت می‌خوان، یه گنجه!",
      img: "https://example.com/u2724de.jpg",
      quantity: 18,
      price: 23500000,
      category: "monitor",
      creator: "Dell",
      stock: true,
      discount: 8,
      rating: 4.6,
      releaseYear: 2025,
    },
    {
      title: "ASUS ROG Strix XG43UQ",
      description:
        "مانیتور 43 اینچی ASUS با رزولوشن 4K که مثل یه سینما گیماتو نشون می‌ده و چشاتو می‌گیره. رفرش‌ریت 144Hz و HDR1000ش برای گیمای سنگین معرکه‌ست. برای گیمرای پریمیوم که دنبال بزرگین، یه انتخاب خفنه!",
      img: "https://example.com/xg43uq.jpg",
      quantity: 10,
      price: 42500000,
      category: "monitor",
      creator: "ASUS",
      stock: true,
      discount: 10,
      rating: 4.9,
      releaseYear: 2023,
    },
    {
      title: "Acer Nitro VG240Y",
      description:
        "مانیتور 24 اینچی Acer با رفرش‌ریت 165Hz که گیمای سریع رو نرم‌تر از ابریشم می‌کنه. پنل IPSش رنگا رو زنده نشون می‌ده و قیمت مناسبش برای گیمرای اقتصادی عالیه. برای گیمای روزمره یه انتخاب باحاله!",
      img: "https://example.com/vg240y.jpg",
      quantity: 22,
      price: 16500000,
      category: "monitor",
      creator: "Acer",
      stock: true,
      discount: 15,
      rating: 4.5,
      releaseYear: 2024,
    },
    {
      title: "LG UltraGear 34GP950G",
      description:
        "مانیتور 34 اینچی LG با رزولوشن UWQHD که انحنای 1900Rش گیماتو غرق‌کننده می‌کنه. رفرش‌ریت 180Hz و G-Syncش لگ رو نابود می‌کنه و پنل IPSش رنگا رو دقیق می‌کنه. برای گیمرای حرفه‌ای یه انتخاب توپه!",
      img: "https://example.com/34gp950g.jpg",
      quantity: 13,
      price: 29500000,
      category: "monitor",
      creator: "LG",
      stock: true,
      discount: 12,
      rating: 4.8,
      releaseYear: 2023,
    },
    {
      title: "Samsung Odyssey G5 (2025)",
      description:
        "مانیتور 32 اینچی Samsung با انحنای 1000R که گیماتو فراگیر می‌کنه و چشاتو می‌گیره. رزولوشن QHD و رفرش‌ریت 165Hzش برای گیمای سنگین کافیه. برای گیمرای باکلاس که دنبال استایلن، یه گنجه!",
      img: "https://example.com/odysseyg5.jpg",
      quantity: 17,
      price: 20500000,
      category: "monitor",
      creator: "Samsung",
      stock: true,
      discount: 10,
      rating: 4.6,
      releaseYear: 2025,
    },
    {
      title: "MSI Optix MPG341CQR",
      description:
        "مانیتور 34 اینچی MSI با رزولوشن UWQHD که انحنای 1800Rش گیماتو غرق‌کننده می‌کنه. رفرش‌ریت 144Hz و RGB پشتش حس گیمری می‌ده. برای گیمرای چندکاره که کیفیت می‌خوان، یه انتخاب شیکه!",
      img: "https://example.com/mpg341cqr.jpg",
      quantity: 19,
      price: 27500000,
      category: "monitor",
      creator: "MSI",
      stock: true,
      discount: 8,
      rating: 4.7,
      releaseYear: 2023,
    },
    {
      title: "BenQ Zowie XL2746K",
      description:
        "مانیتور 27 اینچی BenQ با رفرش‌ریت 240Hz که برای گیمرای esports مثل رعد و برق عمل می‌کنه. پنل TNش زمان پاسخگویی 0.5ms داره و دقتش دشمناتو نابود می‌کنه. برای تورنمنت‌بازای حرفه‌ای یه انتخاب خفنه!",
      img: "https://example.com/xl2746k.jpg",
      quantity: 15,
      price: 24500000,
      category: "monitor",
      creator: "BenQ",
      stock: true,
      discount: 10,
      rating: 4.8,
      releaseYear: 2024,
    },
    {
      title: "Dell Alienware AW2725DF",
      description:
        "مانیتور 27 اینچی Dell با پنل OLED که رنگای مشکی عمیق و زنده‌ای بهت می‌ده. رفرش‌ریت 360Hz و زمان پاسخگویی 0.03ms گیماتو به اوج می‌بره. برای گیمرای پریمیوم که بهترینو می‌خوان، یه گنجه!",
      img: "https://example.com/aw2725df.jpg",
      quantity: 11,
      price: 36500000,
      category: "monitor",
      creator: "Dell",
      stock: true,
      discount: 15,
      rating: 4.9,
      releaseYear: 2025,
    },
    {
      title: "ASUS ROG Swift OLED PG32UCDM",
      description:
        "مانیتور 32 اینچی ASUS با پنل OLED که کنتراست دیوونه‌کننده‌ای داره و گیماتو غرق می‌کنه. رزولوشن 4K و رفرش‌ریت 240Hzش برای گیمای سنگین معرکه‌ست. برای گیمرای لوکس‌پسند یه انتخاب خفنه!",
      img: "https://example.com/pg32ucdm.jpg",
      quantity: 14,
      price: 39500000,
      category: "monitor",
      creator: "ASUS",
      stock: true,
      discount: 10,
      rating: 4.9,
      releaseYear: 2024,
    },
    {
      title: "Acer Predator XB323QK",
      description:
        "مانیتور 32 اینچی Acer با رزولوشن 4K که رفرش‌ریت 144Hzش گیماتو نرم‌تر از کره می‌کنه. پنل IPSش رنگا رو دقیق نشون می‌ده و HDR400ش چشاتو می‌گیره. برای گیمرای باکلاس که کیفیت می‌خوان، یه انتخاب باحاله!",
      img: "https://example.com/xb323qk.jpg",
      quantity: 16,
      price: 30500000,
      category: "monitor",
      creator: "Acer",
      stock: true,
      discount: 12,
      rating: 4.7,
      releaseYear: 2023,
    },
    {
      title: "LG UltraGear 38GN950",
      description:
        "مانیتور 38 اینچی LG با رزولوشن UWQHD که انحنای 1900Rش گیماتو فراگیر می‌کنه. رفرش‌ریت 160Hz و G-Syncش لگ رو نابود می‌کنه و پنل Nano IPSش رنگا رو زنده می‌کنه. برای گیمرای حرفه‌ای یه انتخاب توپه!",
      img: "https://example.com/38gn950.jpg",
      quantity: 13,
      price: 33500000,
      category: "monitor",
      creator: "LG",
      stock: true,
      discount: 10,
      rating: 4.8,
      releaseYear: 2023,
    },
    {
      title: "Samsung Odyssey Ark (2024)",
      description:
        "مانیتور 55 اینچی Samsung با رزولوشن 4K که مثل یه سفینه فضایی گیماتو نشون می‌ده. رفرش‌ریت 165Hz و انحنای 1000Rش گیماتو غرق‌کننده می‌کنه. برای گیمرای لوکس که دنبال غولن، یه گنجه!",
      img: "https://example.com/odysseyark.jpg",
      quantity: 10,
      price: 58500000,
      category: "monitor",
      creator: "Samsung",
      stock: true,
      discount: 8,
      rating: 4.9,
      releaseYear: 2024,
    },

   
    
  ];
  