export const deliverStatusLogs = [
  {
    name: "Sony PlayStation 4 Pro Neo",
    price: 16500000,
    delivered: true,
    img: "https://example.com/ps4proneo.jpg",
    quantity: 1,
    category: "console",
  },
  {
    name: "Microsoft Xbox Series X Halo Edition",
    price: 31500000,
    delivered: false,
    img: "https://example.com/xboxhalo.jpg",
    quantity: 2,
    category: "console",
  },
  {
    name: "Nintendo Switch Lite Pro",
    price: 15500000,
    delivered: true,
    img: "https://example.com/switchlitepro.jpg",
    quantity: 1,
    category: "console",
  },
  {
    name: "Sony PlayStation 5 Digital Edition",
    price: 27500000,
    delivered: false,
    img: "https://example.com/ps5digital.jpg",
    quantity: 1,
    category: "console",
  },
  {
    name: "Microsoft Xbox Series X Slim",
    price: 30500000,
    delivered: true,
    img: "https://example.com/xboxseriesxslim.jpg",
    quantity: 3,
    category: "console",
  },
  {
    name: "Nintendo Switch Pro",
    price: 22500000,
    delivered: true,
    img: "https://example.com/switchpro.jpg",
    quantity: 1,
    category: "console",
  },
  {
    name: "Sony PlayStation Vita Neo",
    price: 14500000,
    delivered: false,
    img: "https://example.com/vitaneo.jpg",
    quantity: 1,
    category: "console",
  },
  {
    name: "Sony PlayStation 5 Digital Edition",
    price: 27500000,
    delivered: true,
    img: "https://example.com/ps5digital.jpg",
    quantity: 2,
    category: "console",
  },
  {
    name: "Microsoft Xbox Series X Halo Edition",
    price: 31500000,
    delivered: false,
    img: "https://example.com/xboxhalo.jpg",
    quantity: 1,
    category: "console",
  },
  {
    name: "Nintendo Switch Lite Pro",
    price: 15500000,
    delivered: true,
    img: "https://example.com/switchlitepro.jpg",
    quantity: 2,
    category: "console",
  },
  {
    name: "Nintendo Switch Pro",
    price: 22500000,
    delivered: false,
    img: "https://example.com/switchpro.jpg",
    quantity: 3,
    category: "console",
  },
  {
    name: "Microsoft Xbox Series X Slim",
    price: 30500000,
    delivered: true,
    img: "https://example.com/xboxseriesxslim.jpg",
    quantity: 1,
    category: "console",
  },
  {
    name: "Sony PlayStation Vita Neo",
    price: 14500000,
    delivered: true,
    img: "https://example.com/vitaneo.jpg",
    quantity: 2,
    category: "console",
  },
  {
    name: "Sony PlayStation 4 Pro Neo",
    price: 16500000,
    delivered: false,
    img: "https://example.com/ps4proneo.jpg",
    quantity: 1,
    category: "console",
  },
  {
    name: "Sony PlayStation 5 Digital Edition",
    price: 27500000,
    delivered: false,
    img: "https://example.com/ps5digital.jpg",
    quantity: 1,
    category: "console",
  },
  {
    name: "Acer Nitro VG240Y",
    price: 16500000,
    delivered: true,
    img: "https://example.com/vg240y.jpg",
    quantity: 2,
    category: "monitor",
  },
  {
    name: "LG UltraGear 34GP950G",
    price: 29500000,
    delivered: false,
    img: "https://example.com/34gp950g.jpg",
    quantity: 1,
    category: "monitor",
  },
  {
    name: "Samsung Odyssey G5 (2025)",
    price: 20500000,
    delivered: true,
    img: "https://example.com/odysseyg5.jpg",
    quantity: 3,
    category: "monitor",
  },
  {
    name: "MSI Optix MPG341CQR",
    price: 27500000,
    delivered: false,
    img: "https://example.com/mpg341cqr.jpg",
    quantity: 1,
    category: "monitor",
  },
  {
    name: "BenQ Zowie XL2746K",
    price: 24500000,
    delivered: true,
    img: "https://example.com/xl2746k.jpg",
    quantity: 2,
    category: "monitor",
  },
  {
    name: "Dell Alienware AW2725DF",
    price: 36500000,
    delivered: true,
    img: "https://example.com/aw2725df.jpg",
    quantity: 1,
    category: "monitor",
  },
  {
    name: "Acer Nitro VG240Y",
    price: 16500000,
    delivered: false,
    img: "https://example.com/vg240y.jpg",
    quantity: 3,
    category: "monitor",
  },
  {
    name: "Samsung Odyssey G5 (2025)",
    price: 20500000,
    delivered: false,
    img: "https://example.com/odysseyg5.jpg",
    quantity: 1,
    category: "monitor",
  },
  {
    name: "LG UltraGear 34GP950G",
    price: 29500000,
    delivered: true,
    img: "https://example.com/34gp950g.jpg",
    quantity: 1,
    category: "monitor",
  },
  {
    name: "Dell Alienware AW2725DF",
    price: 36500000,
    delivered: false,
    img: "https://example.com/aw2725df.jpg",
    quantity: 2,
    category: "monitor",
  },
  {
    name: "MSI Optix MPG341CQR",
    price: 27500000,
    delivered: true,
    img: "https://example.com/mpg341cqr.jpg",
    quantity: 1,
    category: "monitor",
  },
  {
    name: "BenQ Zowie XL2746K",
    price: 24500000,
    delivered: false,
    img: "https://example.com/xl2746k.jpg",
    quantity: 1,
    category: "monitor",
  },
];
