export const salesData = [
    {
      title: "Assassin's Creed Mirage",
      img: "https://example.com/acmirage.jpg",
      quantitySold: 120,
      price: 1100000,
      revenue: 132000000,
      category: "game",
    },
    {
      title: "Spider-Man 2",
      img: "https://example.com/spiderman2.jpg",
      quantitySold: 200,
      price: 1250000,
      revenue: 250000000,
      category: "game",
    },
    {
      title: "Cyberpunk 2077: Phantom Liberty",
      img: "https://example.com/cyberpunkdlc.jpg",
      quantitySold: 175,
      price: 1200000,
      revenue: 210000000,
      category: "game",
    },
    {
      title: "Elden Ring: Shadow of the Erdtree",
      img: "https://example.com/eldenringdlc.jpg",
      quantitySold: 140,
      price: 1300000,
      revenue: 182000000,
      category: "game",
    },
    {
      title: "Final Fantasy XVI",
      img: "https://example.com/ff16.jpg",
      quantitySold: 90,
      price: 1350000,
      revenue: 121500000,
      category: "game",
    },
    {
      title: "Starfield",
      img: "https://example.com/starfield.jpg",
      quantitySold: 150,
      price: 1400000,
      revenue: 210000000,
      category: "game",
    },
    {
      title: "Hogwarts Legacy",
      img: "https://example.com/hogwartslegacy.jpg",
      quantitySold: 180,
      price: 1150000,
      revenue: 207000000,
      category: "game",
    },
    {
      title: "The Legend of Zelda: Tears of the Kingdom",
      img: "https://example.com/zelda.jpg",
      quantitySold: 230,
      price: 950000,
      revenue: 218500000,
      category: "game",
    },
    {
      title: "Diablo IV",
      img: "https://example.com/diablo4.jpg",
      quantitySold: 170,
      price: 1250000,
      revenue: 212500000,
      category: "game",
    },
    {
      title: "Resident Evil 4 Remake",
      img: "https://example.com/re4remake.jpg",
      quantitySold: 200,
      price: 1100000,
      revenue: 220000000,
      category: "game",
    },
    {
      title: "BenQ Mobiuz EX3210R",
      img: "https://example.com/ex3210r.jpg",
      quantity: 17,
      price: 24500000,
      category: "monitor",
    },
    {
      title: "Dell S3222DGM",
      img: "https://example.com/s3222dgm.jpg",
      quantity: 19,
      price: 21500000,
      category: "monitor",
    },
    {
      title: "ASUS TUF VG32AQL1A",
      img: "https://example.com/vg32aql1a.jpg",
      quantity: 15,
      price: 25500000,
      category: "monitor",
    },
    {
      title: "Acer Nitro XZ342CU",
      img: "https://example.com/xz342cu.jpg",
      quantity: 20,
      price: 22500000,
      category: "monitor",
    },
    {
      title: "LG UltraGear 24GN650",
      img: "https://example.com/24gn650.jpg",
      quantity: 22,
      price: 17500000,
      category: "monitor",
    },
    {
      title: "Samsung Odyssey G9 Neo",
      img: "https://example.com/odysseyg9neo.jpg",
      quantity: 12,
      price: 48500000,
      category: "monitor",
    },
    {
      title: "MSI Optix MAG272CQR",
      img: "https://example.com/mag272cqr.jpg",
      quantity: 18,
      price: 19500000,
      category: "monitor",
    },
    {
      title: "BenQ Zowie XL2546X",
      img: "https://example.com/xl2546x.jpg",
      quantity: 16,
      price: 22500000,
      category: "monitor",
    },
    {
      title: "Dell Alienware AW5525QF",
      img: "https://example.com/aw5525qf.jpg",
      quantity: 10,
      price: 59500000,
      category: "monitor",
    },
    {
      title: "Sony PlayStation 5 Pro",
      img: "https://example.com/ps5pro.jpg",
      quantity: 10,
      price: 32500000,
      category: "console",
    },
    {
      title: "Microsoft Xbox Series X Elite",
      img: "https://example.com/xboxseriesxelite.jpg",
      quantity: 12,
      price: 29500000,
      category: "console",
    },
    {
      title: "Nintendo Switch 2",
      img: "https://example.com/switch2.jpg",
      quantity: 15,
      price: 24500000,
      category: "console",
    },
    {
      title: "Sony PlayStation 5 Slim",
      img: "https://example.com/ps5slim.jpg",
      quantity: 18,
      price: 28500000,
      category: "console",
    },
    {
      title: "Microsoft Xbox Series S Next",
      img: "https://example.com/xboxseriesnext.jpg",
      quantity: 20,
      price: 19500000,
      category: "console",
    },
    {
      title: "Nintendo Switch OLED",
      img: "https://example.com/switcholed.jpg",
      quantity: 14,
      price: 18500000,
      category: "console",
    },
    {
      title: "Sony PlayStation 4 Pro Neo",
      img: "https://example.com/ps4proneo.jpg",
      quantity: 16,
      price: 16500000,
      category: "console",
    },
    {
      title: "Microsoft Xbox Series X Halo Edition",
      img: "https://example.com/xboxhalo.jpg",
      quantity: 11,
      price: 31500000,
      category: "console",
    },
    {
      title: "Nintendo Switch Lite Pro",
      img: "https://example.com/switchlitepro.jpg",
      quantity: 19,
      price: 15500000,
      category: "console",
    },
    {
      title: "Sony PlayStation 5 Digital Edition",
      img: "https://example.com/ps5digital.jpg",
      quantity: 13,
      price: 27500000,
      category: "console",
    },
    {
      title: "Microsoft Xbox Series X Slim",
      img: "https://example.com/xboxseriesxslim.jpg",
      quantity: 17,
      price: 30500000,
      category: "console",
    },
    {
      title: "Nintendo Switch Pro",
      img: "https://example.com/switchpro.jpg",
      quantity: 15,
      price: 22500000,
      category: "console",
    },
  ];
  